<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Summarizing data | Retail Marketing Analytics 2026</title>
  <meta name="description" content="An Introduction to Data Analytics Using R" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Summarizing data | Retail Marketing Analytics 2026" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An Introduction to Data Analytics Using R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Summarizing data | Retail Marketing Analytics 2026" />
  
  <meta name="twitter:description" content="An Introduction to Data Analytics Using R" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="data-handling.html"/>
<link rel="next" href="statistical-inference.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">RMA 2026</a></strong></li>

<li class="divider"></li>
<li class="part"><span><b>I Course outline</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#course-structure"><i class="fa fa-check"></i>Course structure</a>
<ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#contents"><i class="fa fa-check"></i>Contents</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#grading"><i class="fa fa-check"></i>Grading</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#course-materials"><i class="fa fa-check"></i>Course materials</a>
<ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#main-reference"><i class="fa fa-check"></i>Main reference</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#further-readings"><i class="fa fa-check"></i>Further readings</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#discussion-forum"><i class="fa fa-check"></i>Discussion forum</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#other-web-resources"><i class="fa fa-check"></i>Other web-resources</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#contact"><i class="fa fa-check"></i>Contact</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Lecture notes</b></span></li>
<li class="chapter" data-level="1" data-path="preliminaries.html"><a href="preliminaries.html"><i class="fa fa-check"></i><b>1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="1.1" data-path="preliminaries.html"><a href="preliminaries.html#marketing-foundations-recap"><i class="fa fa-check"></i><b>1.1</b> Marketing foundations (recap)</a></li>
<li class="chapter" data-level="1.2" data-path="preliminaries.html"><a href="preliminaries.html#the-research-process"><i class="fa fa-check"></i><b>1.2</b> The research process</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="preliminaries.html"><a href="preliminaries.html#research-question-and-hypothesis"><i class="fa fa-check"></i><b>1.2.1</b> Research question and hypothesis</a></li>
<li class="chapter" data-level="1.2.2" data-path="preliminaries.html"><a href="preliminaries.html#choosing-a-research-design"><i class="fa fa-check"></i><b>1.2.2</b> Choosing a research design</a></li>
<li class="chapter" data-level="1.2.3" data-path="preliminaries.html"><a href="preliminaries.html#collecting-data"><i class="fa fa-check"></i><b>1.2.3</b> Collecting data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="preliminaries.html"><a href="preliminaries.html#learning-check"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="preliminaries.html"><a href="preliminaries.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html"><i class="fa fa-check"></i><b>2</b> Getting started with R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#how-to-download-and-install-r-and-rstudio"><i class="fa fa-check"></i><b>2.1</b> How to download and install R and RStudio</a></li>
<li class="chapter" data-level="2.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#the-r-studio-interface"><i class="fa fa-check"></i><b>2.2</b> The R Studio interface</a></li>
<li class="chapter" data-level="2.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#functions"><i class="fa fa-check"></i><b>2.3</b> Functions</a></li>
<li class="chapter" data-level="2.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#packages"><i class="fa fa-check"></i><b>2.4</b> Packages</a></li>
<li class="chapter" data-level="2.5" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#a-typical-r-session"><i class="fa fa-check"></i><b>2.5</b> A typical R session</a></li>
<li class="chapter" data-level="2.6" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#getting-help"><i class="fa fa-check"></i><b>2.6</b> Getting help</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-handling.html"><a href="data-handling.html"><i class="fa fa-check"></i><b>3</b> Data handling</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-handling.html"><a href="data-handling.html#data-import-and-export"><i class="fa fa-check"></i><b>3.1</b> Data import and export</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-handling.html"><a href="data-handling.html#getting-data-for-this-course"><i class="fa fa-check"></i><b>3.1.1</b> Getting data for this course</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-handling.html"><a href="data-handling.html#export-data"><i class="fa fa-check"></i><b>3.1.2</b> Export data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-handling.html"><a href="data-handling.html#basic-data-handling"><i class="fa fa-check"></i><b>3.2</b> Basic data handling</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-handling.html"><a href="data-handling.html#creating-objects"><i class="fa fa-check"></i><b>3.2.1</b> Creating objects</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-handling.html"><a href="data-handling.html#data-types"><i class="fa fa-check"></i><b>3.2.2</b> Data types</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-handling.html"><a href="data-handling.html#data-structures"><i class="fa fa-check"></i><b>3.2.3</b> Data structures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-handling.html"><a href="data-handling.html#learning-check-1"><i class="fa fa-check"></i>Learning check</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="summarizing-data.html"><a href="summarizing-data.html"><i class="fa fa-check"></i><b>4</b> Summarizing data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="summarizing-data.html"><a href="summarizing-data.html#summary-statistics"><i class="fa fa-check"></i><b>4.1</b> Summary statistics</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables"><i class="fa fa-check"></i><b>4.1.1</b> Categorical variables</a></li>
<li class="chapter" data-level="4.1.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables"><i class="fa fa-check"></i><b>4.1.2</b> Continuous variables</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="summarizing-data.html"><a href="summarizing-data.html#data-visualization"><i class="fa fa-check"></i><b>4.2</b> Data visualization</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables-1"><i class="fa fa-check"></i><b>4.2.1</b> Categorical variables</a></li>
<li class="chapter" data-level="4.2.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables-1"><i class="fa fa-check"></i><b>4.2.2</b> Continuous variables</a></li>
<li class="chapter" data-level="4.2.3" data-path="summarizing-data.html"><a href="summarizing-data.html#saving-plots-on-your-device"><i class="fa fa-check"></i><b>4.2.3</b> Saving plots on your device</a></li>
<li class="chapter" data-level="4.2.4" data-path="summarizing-data.html"><a href="summarizing-data.html#ggplot-extensions"><i class="fa fa-check"></i><b>4.2.4</b> ggplot extensions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="summarizing-data.html"><a href="summarizing-data.html#learning-check-2"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="summarizing-data.html"><a href="summarizing-data.html#references-1"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>5</b> Statistical inference</a>
<ul>
<li class="chapter" data-level="5.1" data-path="statistical-inference.html"><a href="statistical-inference.html#if-we-knew-it-all"><i class="fa fa-check"></i><b>5.1</b> If we knew it all</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="statistical-inference.html"><a href="statistical-inference.html#sampling-from-a-known-population"><i class="fa fa-check"></i><b>5.1.1</b> Sampling from a known population</a></li>
<li class="chapter" data-level="5.1.2" data-path="statistical-inference.html"><a href="statistical-inference.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>5.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="statistical-inference.html"><a href="statistical-inference.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>5.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="5.3" data-path="statistical-inference.html"><a href="statistical-inference.html#using-what-we-actually-know"><i class="fa fa-check"></i><b>5.3</b> Using what we actually know</a></li>
<li class="chapter" data-level="5.4" data-path="statistical-inference.html"><a href="statistical-inference.html#confidence-intervals-for-the-sample-mean"><i class="fa fa-check"></i><b>5.4</b> Confidence Intervals for the Sample Mean</a></li>
<li class="chapter" data-level="5.5" data-path="statistical-inference.html"><a href="statistical-inference.html#null-hypothesis-statistical-testing-nhst"><i class="fa fa-check"></i><b>5.5</b> Null Hypothesis Statistical Testing (NHST)</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="statistical-inference.html"><a href="statistical-inference.html#the-null-hypothesis"><i class="fa fa-check"></i><b>5.5.1</b> The null hypothesis</a></li>
<li class="chapter" data-level="5.5.2" data-path="statistical-inference.html"><a href="statistical-inference.html#statistical-inference-on-a-sample"><i class="fa fa-check"></i><b>5.5.2</b> Statistical inference on a sample</a></li>
<li class="chapter" data-level="5.5.3" data-path="statistical-inference.html"><a href="statistical-inference.html#nhst-considerations"><i class="fa fa-check"></i><b>5.5.3</b> NHST considerations</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="statistical-inference.html"><a href="statistical-inference.html#learning-check-3"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="statistical-inference.html"><a href="statistical-inference.html#references-2"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="supervised-learning.html"><a href="supervised-learning.html"><i class="fa fa-check"></i><b>6</b> Supervised learning</a>
<ul>
<li class="chapter" data-level="6.1" data-path="supervised-learning.html"><a href="supervised-learning.html#linear-regression"><i class="fa fa-check"></i><b>6.1</b> Linear regression</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="supervised-learning.html"><a href="supervised-learning.html#correlation"><i class="fa fa-check"></i><b>6.1.1</b> Correlation</a></li>
<li class="chapter" data-level="6.1.2" data-path="supervised-learning.html"><a href="supervised-learning.html#regression-analysis"><i class="fa fa-check"></i><b>6.1.2</b> Regression analysis</a></li>
<li class="chapter" data-level="6.1.3" data-path="supervised-learning.html"><a href="supervised-learning.html#categorical-predictors"><i class="fa fa-check"></i><b>6.1.3</b> Categorical predictors</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="supervised-learning.html"><a href="supervised-learning.html#logistic-regression-extra"><i class="fa fa-check"></i><b>6.2</b> <span style="color: purple;">Logistic regression (extra)</span></a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="supervised-learning.html"><a href="supervised-learning.html#motivation-and-intuition"><i class="fa fa-check"></i><b>6.2.1</b> Motivation and intuition</a></li>
<li class="chapter" data-level="6.2.2" data-path="supervised-learning.html"><a href="supervised-learning.html#technical-details-of-the-model"><i class="fa fa-check"></i><b>6.2.2</b> Technical details of the model</a></li>
<li class="chapter" data-level="6.2.3" data-path="supervised-learning.html"><a href="supervised-learning.html#estimation-in-r"><i class="fa fa-check"></i><b>6.2.3</b> Estimation in R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="supervised-learning.html"><a href="supervised-learning.html#learning-check-4"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="supervised-learning.html"><a href="supervised-learning.html#references-3"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="unsupervised-learning-extra.html"><a href="unsupervised-learning-extra.html"><i class="fa fa-check"></i><b>7</b> <span style="color: purple;">Unsupervised learning (extra)</span></a>
<ul>
<li class="chapter" data-level="7.1" data-path="unsupervised-learning-extra.html"><a href="unsupervised-learning-extra.html#principal-component-analysis"><i class="fa fa-check"></i><b>7.1</b> Principal component analysis</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="unsupervised-learning-extra.html"><a href="unsupervised-learning-extra.html#introduction-1"><i class="fa fa-check"></i><b>7.1.1</b> Introduction</a></li>
<li class="chapter" data-level="7.1.2" data-path="unsupervised-learning-extra.html"><a href="unsupervised-learning-extra.html#steps-in-factor-analysis"><i class="fa fa-check"></i><b>7.1.2</b> Steps in factor analysis</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="unsupervised-learning-extra.html"><a href="unsupervised-learning-extra.html#cluster-analysis"><i class="fa fa-check"></i><b>7.2</b> Cluster analysis</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="unsupervised-learning-extra.html"><a href="unsupervised-learning-extra.html#k-means"><i class="fa fa-check"></i><b>7.2.1</b> K-Means</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="unsupervised-learning-extra.html"><a href="unsupervised-learning-extra.html#learning-check-5"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="unsupervised-learning-extra.html"><a href="unsupervised-learning-extra.html#references-4"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="part"><span><b>III Assignments</b></span></li>
<li class="chapter" data-level="8" data-path="r-markdown.html"><a href="r-markdown.html"><i class="fa fa-check"></i><b>8</b> R Markdown</a>
<ul>
<li class="chapter" data-level="8.1" data-path="r-markdown.html"><a href="r-markdown.html#introduction-to-r-markdown"><i class="fa fa-check"></i><b>8.1</b> Introduction to R Markdown</a>
<ul>
<li class="chapter" data-level="" data-path="r-markdown.html"><a href="r-markdown.html#creating-a-new-r-markdown-document"><i class="fa fa-check"></i>Creating a new R Markdown document</a></li>
<li class="chapter" data-level="" data-path="r-markdown.html"><a href="r-markdown.html#text-and-equations"><i class="fa fa-check"></i>Text and Equations</a></li>
<li class="chapter" data-level="" data-path="r-markdown.html"><a href="r-markdown.html#r-code"><i class="fa fa-check"></i>R-Code</a></li>
<li class="chapter" data-level="" data-path="r-markdown.html"><a href="r-markdown.html#latex-math"><i class="fa fa-check"></i>LaTeX Math</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV FAQ</b></span></li>
<li class="chapter" data-level="9" data-path="faq.html"><a href="faq.html"><i class="fa fa-check"></i><b>9</b> FAQ</a>
<ul>
<li class="chapter" data-level="9.1" data-path="faq.html"><a href="faq.html#common-error-messages"><i class="fa fa-check"></i><b>9.1</b> Common error messages</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#a-general-note-on-error-messages"><i class="fa fa-check"></i>A general note on error messages</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-filefile-rt-cannot-open-the-connection"><i class="fa fa-check"></i>Error in file(file, “rt”): cannot open the connection</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-unexpected-symbol-in-call"><i class="fa fa-check"></i>Error: unexpected ‘SYMBOL’ in “CALL”</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-call-object-of-type-closure-is-not-subsettable"><i class="fa fa-check"></i>Error in CALL : object of type ‘closure’ is not subsettable</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-call_with_-operator-is-invalid-for-atomic-vectors"><i class="fa fa-check"></i>Error in CALL_WITH_$: $ operator is invalid for atomic vectors</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-call-object-name-not-found"><i class="fa fa-check"></i>Error in CALL: object ‘NAME’ not found</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-call-could-not-find-function-function"><i class="fa fa-check"></i>Error in CALL: could not find function “FUNCTION”</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-call-incorrect-number-of-dimension"><i class="fa fa-check"></i>Error in CALL: incorrect number of dimension</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="faq.html"><a href="faq.html#installation-of-r-packages"><i class="fa fa-check"></i><b>9.2</b> Installation of R packages</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#what-are-the-different-ways-to-install-r-packages"><i class="fa fa-check"></i>What are the different ways to install R packages?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#i-cannot-install-packages-due-to-error-in-contrib.urlrepossource-or-warning-message-package-packagename-is-not-available-for-this-version-of-r"><i class="fa fa-check"></i>I cannot install packages due to “Error in contrib.url(repos,”source”)” or “Warning message: package ‘PACKAGENAME’ is not available for this version of R”</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#some-libraries-with-graphical-output-e.g.-summarytools-magick-fail-to-installload-properly-on-macos"><i class="fa fa-check"></i>Some libraries with graphical output (e.g., summarytools, magick) fail to install/load properly on MacOS</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#i-cannot-install-some-packages-on-macos"><i class="fa fa-check"></i>I cannot install some packages on MacOS</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="faq.html"><a href="faq.html#issues-with-statistics-and-data"><i class="fa fa-check"></i><b>9.3</b> Issues with statistics and data</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#why-does-a-multi-item-scale-lead-to-increased-reliability"><i class="fa fa-check"></i>Why does a multi-item scale lead to increased reliability?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#why-can-demeaningstandardization-lead-to-missing-values"><i class="fa fa-check"></i>Why can demeaning/standardization lead to missing values?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#the-confidence-interval-ci-of-the-mean-seems-very-small-compared-to-the-dispersion-of-my-sample.-can-this-be-correct"><i class="fa fa-check"></i>The confidence interval (CI) of the mean seems very small compared to the dispersion of my sample. Can this be correct?</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="faq.html"><a href="faq.html#errors-related-to-specific-methods"><i class="fa fa-check"></i><b>9.4</b> Errors related to specific methods</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#logistic-regression"><i class="fa fa-check"></i>Logistic regression</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#when-using-logistic-regression-error-in-weights-y-non-numeric-argument-to-binary-operator"><i class="fa fa-check"></i>When using logistic regression: Error in weights * y : non-numeric argument to binary operator</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="faq.html"><a href="faq.html#general-settings-and-options"><i class="fa fa-check"></i><b>9.5</b> General settings and options</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#numbers-are-formatted-weirdly"><i class="fa fa-check"></i>Numbers are formatted weirdly</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="faq.html"><a href="faq.html#data-visualizationoutput-issues"><i class="fa fa-check"></i><b>9.6</b> Data visualization/output issues</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#how-can-the-geom-colors-in-a-ggplot-be-changed"><i class="fa fa-check"></i>How can the <code>geom</code> colors in a <code>ggplot</code> be changed?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#why-are-some-histograms-displayed-differently"><i class="fa fa-check"></i>Why are some histograms displayed differently?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#some-labels-in-plots-are-cut-off.-how-can-i-extend-the-plot-margins"><i class="fa fa-check"></i>Some labels in plots are cut off. How can I extend the plot margins?</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="faq.html"><a href="faq.html#issues-with-functions-and-function-arguments"><i class="fa fa-check"></i><b>9.7</b> Issues with functions and function arguments</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#problems-with-factor-and-as.factor"><i class="fa fa-check"></i>Problems with <code>factor</code> and <code>as.factor</code></a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#how-can-i-find-an-explanation-of-the-output-of-a-function"><i class="fa fa-check"></i>How can I find an explanation of the output of a function?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#what-does-the-margin-argument-do"><i class="fa fa-check"></i>What does the <code>MARGIN</code> argument do?</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="faq.html"><a href="faq.html#issues-with-r-markdown"><i class="fa fa-check"></i><b>9.8</b> Issues with R Markdown</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#i-get-an-error-when-knitting-to-pdf-but-it-works-for-html"><i class="fa fa-check"></i>I get an error when <code>knit</code>ting to PDF but it works for HTML</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#i-am-not-sure-where-r-code-latex-math-and-text-go"><i class="fa fa-check"></i>I am not sure where R-code, LaTeX math, and text go</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="faq.html"><a href="faq.html#new-questions"><i class="fa fa-check"></i><b>9.9</b> New questions</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Retail Marketing Analytics 2026</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="summarizing-data" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Summarizing data<a href="summarizing-data.html#summarizing-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="summary-statistics" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Summary statistics<a href="summarizing-data.html#summary-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This section discusses how to produce and analyze basic summary statistics. Summary statistics are often used to describe variables in terms of 1) the central tendency of the frequency distribution, and 2) the dispersion of values.</p>
<p><br></p>
<p>A <strong>measure of central tendency</strong> is a single value that attempts to describe the data by identifying the central position within the data. There are various measures of central tendency as the following table shows.</p>
<table>
<colgroup>
<col width="10%" />
<col width="76%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th>Description</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean</td>
<td>The average value when you sum up all elements and divide by the number of elements</td>
<td><span class="math inline">\(\bar{X}=\frac{\sum_{i=1}^{n}{X_i}}{n}\)</span></td>
</tr>
<tr class="even">
<td>Mode</td>
<td>The value that occurs most frequently (i.e., the highest peak of the frequency distribution)</td>
<td></td>
</tr>
<tr class="odd">
<td>Median</td>
<td>The middle value when the data are arranged in ascending or descending order (i.e., the 50th percentile)</td>
<td></td>
</tr>
</tbody>
</table>
<p><br></p>
<p>The <strong>dispersion</strong> refers to the degree to which the data is distributed around the central tendency and can be described in terms of the range, interquartile range, variance, and standard deviation.</p>
<table>
<colgroup>
<col width="10%" />
<col width="76%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th>Description</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Range</td>
<td>The difference between the largest and smallest values in the sample</td>
<td><span class="math inline">\(Range=X_{largest}-X_{smallest}\)</span></td>
</tr>
<tr class="even">
<td>Interquartile range</td>
<td>The range of the middle 50% of scores</td>
<td><span class="math inline">\(IQR=Q_3-Q_1\)</span></td>
</tr>
<tr class="odd">
<td>Variance</td>
<td>The mean squared deviation of all the values of the mean</td>
<td><span class="math inline">\(s^2=\frac{1}{n-1}*\sum_{i=1}^{n}{(X_i-\bar{X})^2}\)</span></td>
</tr>
<tr class="even">
<td>Standard deviation</td>
<td>The square root of the variance</td>
<td><span class="math inline">\(s_x=\sqrt{s^2}\)</span></td>
</tr>
</tbody>
</table>
<p><br></p>
<p>The answer to the question which measures to use depends on the level of measurement. Based on the discussion in chapter 1, we make a distinction between categorical and continuous variables, for which different statistics are permissible as summarized in the following table.</p>
<table style="width:100%;">
<colgroup>
<col width="28%" />
<col width="28%" />
<col width="28%" />
<col width="6%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th>OK to compute…</th>
<th>Nominal</th>
<th>Ordinal</th>
<th>Interval</th>
<th>Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>frequency distribution</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>median and percentiles</td>
<td>No</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>mean, standard deviation, standard error of the mean</td>
<td>No</td>
<td>No</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>ratio, or coefficient of variation</td>
<td>No</td>
<td>No</td>
<td>No</td>
<td>Yes</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>As an example data set, we will be using a data set containing music streaming data from a popular streaming service. Let’s load and inspect the data first.</p>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Date"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Store"],"name":[2],"type":["chr"],"align":["left"]},{"label":["Category"],"name":[3],"type":["chr"],"align":["left"]},{"label":["Brand"],"name":[4],"type":["chr"],"align":["left"]},{"label":["Sales_Amount"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Units_Sold"],"name":[6],"type":["int"],"align":["right"]},{"label":["Customer_Age"],"name":[7],"type":["int"],"align":["right"]}],"data":[{"1":"2023-11-30","2":"Store 3","3":"Grocery","4":"Trader Joe's","5":"26.32","6":"17","7":"29"},{"1":"2023-08-04","2":"Store 1","3":"Toys","4":"Mattel","5":"270.08","6":"5","7":"32"},{"1":"2023-02-26","2":"Store 6","3":"Clothing","4":"Puma","5":"372.76","6":"1","7":"31"},{"1":"2023-07-17","2":"Store 7","3":"Electronics","4":"LG","5":"1235.69","6":"3","7":"38"},{"1":"2023-11-03","2":"Store 4","3":"Furniture","4":"West Elm","5":"825.87","6":"1","7":"31"},{"1":"2023-06-03","2":"Store 1","3":"Grocery","4":"Walmart","5":"61.04","6":"9","7":"18"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre><code>## [1] 5000    7</code></pre>
<p>The data set contains information about several purchases made in a number of stores in 2023. The <code>dim()</code>-function returns the dimensions of the data frame (i.e., the number of rows and columns). As can be seen, the data set comprises information for 5000 transactions and 7 variables (columns). The variables in the data set are:</p>
<ul>
<li>Date: date of purchase</li>
<li>Store: Store ID/number</li>
<li>Category: product category of the purchased item</li>
<li>Brand: name of the brand of the purchased item</li>
<li>Sales_Amount: the monetary value of the purchase (i.e., store’s revenue)</li>
<li>Units_Sold: number of units purchased</li>
<li>Customer_Age: the age of the customer who made the purchase</li>
</ul>
<p>In a first step, we need to make sure all variables are in the correct format, according to these variable definitions:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="summarizing-data.html#cb76-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb76-2"><a href="summarizing-data.html#cb76-2" tabindex="-1"></a>sales_data <span class="ot">&lt;-</span> sales_data <span class="sc">%&gt;%</span> <span class="co"># pipe data into mutate</span></span>
<span id="cb76-3"><a href="summarizing-data.html#cb76-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">as.Date</span>(Date), <span class="co"># convert to date</span></span>
<span id="cb76-4"><a href="summarizing-data.html#cb76-4" tabindex="-1"></a>         <span class="at">Store =</span> <span class="fu">as.factor</span>(Store), <span class="co"># convert to factor w. new labels</span></span>
<span id="cb76-5"><a href="summarizing-data.html#cb76-5" tabindex="-1"></a>         <span class="at">Category =</span> <span class="fu">as.factor</span>(Category), <span class="co"># convert to factor with values as labels</span></span>
<span id="cb76-6"><a href="summarizing-data.html#cb76-6" tabindex="-1"></a>         <span class="at">Brand =</span> <span class="fu">as.factor</span>(Brand)) </span>
<span id="cb76-7"><a href="summarizing-data.html#cb76-7" tabindex="-1"></a><span class="fu">head</span>(sales_data)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Date"],"name":[1],"type":["date"],"align":["right"]},{"label":["Store"],"name":[2],"type":["fct"],"align":["left"]},{"label":["Category"],"name":[3],"type":["fct"],"align":["left"]},{"label":["Brand"],"name":[4],"type":["fct"],"align":["left"]},{"label":["Sales_Amount"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Units_Sold"],"name":[6],"type":["int"],"align":["right"]},{"label":["Customer_Age"],"name":[7],"type":["int"],"align":["right"]}],"data":[{"1":"2023-11-30","2":"Store 3","3":"Grocery","4":"Trader Joe's","5":"26.32","6":"17","7":"29"},{"1":"2023-08-04","2":"Store 1","3":"Toys","4":"Mattel","5":"270.08","6":"5","7":"32"},{"1":"2023-02-26","2":"Store 6","3":"Clothing","4":"Puma","5":"372.76","6":"1","7":"31"},{"1":"2023-07-17","2":"Store 7","3":"Electronics","4":"LG","5":"1235.69","6":"3","7":"38"},{"1":"2023-11-03","2":"Store 4","3":"Furniture","4":"West Elm","5":"825.87","6":"1","7":"31"},{"1":"2023-06-03","2":"Store 1","3":"Grocery","4":"Walmart","5":"61.04","6":"9","7":"18"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>In the following sections, we will inspect the data in more detail.</p>
<div id="categorical-variables" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Categorical variables<a href="summarizing-data.html#categorical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Categorical variables contain a finite number of categories or distinct groups and are also known as qualitative or non-metric variables. There are different types of categorical variables:</p>
<ul>
<li><strong>Nominal variables</strong>: variables that have two or more categories but no logical order (e.g., store ID, brand name). A dichotomous variable (also referred to as dummy variable or binary variable) is simply a nominal variable that only has two categories (absent in this data set).</li>
<li><strong>Ordinal variables</strong>: variables that have two or more categories that can also be ordered or ranked (absent in this data set).</li>
</ul>
<p>Let’s now start to investigate the <strong>nominal variables</strong> in our data set.</p>
<p>As the table above shows, the only permissible operation with nominal variables is counting. That is, we can inspect the frequency distribution, which tells us how many observations we have per category. The <code>table()</code> function creates a frequency table that counts how many observations we have in each category.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="summarizing-data.html#cb77-1" tabindex="-1"></a><span class="fu">table</span>(sales_data<span class="sc">$</span>Category)  <span class="co">#absolute frequencies</span></span></code></pre></div>
<pre><code>## 
##    Clothing Electronics   Furniture     Grocery      Sports        Toys 
##        1265         490         286        1746         603         610</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="summarizing-data.html#cb79-1" tabindex="-1"></a><span class="fu">table</span>(sales_data<span class="sc">$</span>Store)  <span class="co">#absolute frequencies</span></span></code></pre></div>
<pre><code>## 
##  Store 1 Store 10  Store 2  Store 3  Store 4  Store 5  Store 6  Store 7 
##      494      506      514      522      461      488      502      465 
##  Store 8  Store 9 
##      516      532</code></pre>
<p>The numbers associated with the factor level in the output tell you, how many observations there are per category. For example, there are 1265 purchases from the Clothing category; also, 532 are from Store No. 9.</p>
<p>Often, we are interested in the relative frequencies (share of observations), which can be obtained by using the <code>prop.table()</code> function.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="summarizing-data.html#cb81-1" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(sales_data<span class="sc">$</span>Category))  <span class="co">#relative frequencies</span></span></code></pre></div>
<pre><code>## 
##    Clothing Electronics   Furniture     Grocery      Sports        Toys 
##      0.2530      0.0980      0.0572      0.3492      0.1206      0.1220</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="summarizing-data.html#cb83-1" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(sales_data<span class="sc">$</span>Store))  <span class="co">#relative frequencies</span></span></code></pre></div>
<pre><code>## 
##  Store 1 Store 10  Store 2  Store 3  Store 4  Store 5  Store 6  Store 7 
##   0.0988   0.1012   0.1028   0.1044   0.0922   0.0976   0.1004   0.0930 
##  Store 8  Store 9 
##   0.1032   0.1064</code></pre>
<p>Now the output gives you the relative frequencies. For example, the share of purchases (transactions) of groceries is ~34.9%, ~10.3% of purchases are from Store number 2.</p>
<p>Note that the above output shows the overall relative frequencies. In many cases, it is meaningful to consider conditional relative frequencies. This can be achieved by adding a <code>,1</code> to the <code>prop.table()</code> command, which tells R to compute the relative frequencies by row (which is in our case the Store variable). The following code can be used to show the relative frequency of purchases from specific categories by store</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="summarizing-data.html#cb85-1" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(<span class="fu">select</span>(sales_data, Store, Category)),</span>
<span id="cb85-2"><a href="summarizing-data.html#cb85-2" tabindex="-1"></a>    <span class="dv">1</span>)  <span class="co">#conditional relative frequencies</span></span></code></pre></div>
<pre><code>##           Category
## Store        Clothing Electronics  Furniture    Grocery     Sports       Toys
##   Store 1  0.26315789  0.08906883 0.05465587 0.34412955 0.11133603 0.13765182
##   Store 10 0.21541502  0.11264822 0.05533597 0.35177866 0.13241107 0.13241107
##   Store 2  0.27237354  0.08171206 0.05642023 0.35019455 0.12062257 0.11867704
##   Store 3  0.24329502  0.10536398 0.04214559 0.34674330 0.12452107 0.13793103
##   Store 4  0.26030369  0.09327549 0.05856833 0.36008677 0.11496746 0.11279826
##   Store 5  0.25819672  0.10655738 0.06352459 0.33196721 0.12295082 0.11680328
##   Store 6  0.23505976  0.07569721 0.07370518 0.34462151 0.14741036 0.12350598
##   Store 7  0.24301075  0.10752688 0.04516129 0.36559140 0.11397849 0.12473118
##   Store 8  0.29844961  0.09496124 0.06201550 0.33527132 0.10852713 0.10077519
##   Store 9  0.24060150  0.11278195 0.06015038 0.36278195 0.10902256 0.11466165</code></pre>
<p>As can be seen, the the share of transactions from the Clothing category is high in all stores, with the highest share of ~30% of transactions in Store 8.</p>
</div>
<div id="continuous-variables" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Continuous variables<a href="summarizing-data.html#continuous-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="descriptive-statistics" class="section level4 hasAnchor" number="4.1.2.1">
<h4><span class="header-section-number">4.1.2.1</span> Descriptive statistics<a href="summarizing-data.html#descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Continuous variables (also know as metric variables) are numeric variables that can take on any value on a measurement scale (i.e., there is an infinite number of values between any two values). There are different types of continuous variables as we have seen in chapter 1:</p>
<ul>
<li><strong>Interval variables</strong>: while the zero point is arbitrary, equal intervals on the scale represent equal differences in the property being measured. E.g., on a temperature scale measured in Celsius the difference between a temperature of 15 degrees and 25 degrees is the same difference as between 25 degrees and 35 degrees but the zero point is arbitrary (there are different scales to measure temperature, such as Fahrenheit or Celsius, and zero in this case doesn’t indicate the absence of temperature).</li>
<li><strong>Ratio variables</strong>: has all the properties of an interval variable, but also has an absolute zero point. When the variable equals 0.0, it means that there is none of that variable (e.g., sales amount and customer age in our example).</li>
</ul>
<p>For interval and ratio variables we can compute the mean as a measure of central tendency, as well as the variance and the standard deviation as measures of dispersion. Computing descriptive statistics for continuous variables is easy and there are many functions. The easiest are:</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="summarizing-data.html#cb87-1" tabindex="-1"></a><span class="co"># average customer age</span></span>
<span id="cb87-2"><a href="summarizing-data.html#cb87-2" tabindex="-1"></a>avg_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(sales_data<span class="sc">$</span>Customer_Age)</span>
<span id="cb87-3"><a href="summarizing-data.html#cb87-3" tabindex="-1"></a>avg_age</span></code></pre></div>
<pre><code>## [1] 35.58</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="summarizing-data.html#cb89-1" tabindex="-1"></a><span class="co"># median customer age</span></span>
<span id="cb89-2"><a href="summarizing-data.html#cb89-2" tabindex="-1"></a>median_age <span class="ot">&lt;-</span> <span class="fu">median</span>(sales_data<span class="sc">$</span>Customer_Age)</span>
<span id="cb89-3"><a href="summarizing-data.html#cb89-3" tabindex="-1"></a>median_age</span></code></pre></div>
<pre><code>## [1] 35</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="summarizing-data.html#cb91-1" tabindex="-1"></a><span class="co"># or using quantile()</span></span>
<span id="cb91-2"><a href="summarizing-data.html#cb91-2" tabindex="-1"></a>median_age <span class="ot">&lt;-</span> <span class="fu">quantile</span>(sales_data<span class="sc">$</span>Customer_Age, <span class="fl">0.5</span>,</span>
<span id="cb91-3"><a href="summarizing-data.html#cb91-3" tabindex="-1"></a>    <span class="at">type =</span> <span class="dv">1</span>)</span>
<span id="cb91-4"><a href="summarizing-data.html#cb91-4" tabindex="-1"></a>median_age</span></code></pre></div>
<pre><code>## 50% 
##  35</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="summarizing-data.html#cb93-1" tabindex="-1"></a><span class="co"># customer age by percentiles</span></span>
<span id="cb93-2"><a href="summarizing-data.html#cb93-2" tabindex="-1"></a><span class="fu">quantile</span>(sales_data<span class="sc">$</span>Customer_Age, <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>),</span>
<span id="cb93-3"><a href="summarizing-data.html#cb93-3" tabindex="-1"></a>    <span class="at">type =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 25% 50% 75% 
##  27  35  43</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="summarizing-data.html#cb95-1" tabindex="-1"></a><span class="co"># mode customer age</span></span>
<span id="cb95-2"><a href="summarizing-data.html#cb95-2" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb95-3"><a href="summarizing-data.html#cb95-3" tabindex="-1"></a>mode_age <span class="ot">&lt;-</span> <span class="fu">Mode</span>(sales_data<span class="sc">$</span>Customer_Age)</span>
<span id="cb95-4"><a href="summarizing-data.html#cb95-4" tabindex="-1"></a>mode_age</span></code></pre></div>
<pre><code>## [1] 18
## attr(,&quot;freq&quot;)
## [1] 382</code></pre>
<p>We can also use functions that return multiple statistics at once; those are available in different packages that let you calculate summary statistics (including the <code>summary()</code> function from the <code>base</code> package). In this tutorial, we will use the <code>describe()</code> function from the <code>psych</code> package. Note that you could just as well use other packages to compute the descriptive statistics (e.g., the <code>stat.desc()</code> function from the <code>pastecs</code> package). Which one you choose depends on what type of information you seek (the results provide slightly different information) and on personal preferences.</p>
<p>We could, for example, compute the summary statistics for the variables “sales amount”, “units sold”, and “customer age” in our data set as follows:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="summarizing-data.html#cb97-1" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb97-2"><a href="summarizing-data.html#cb97-2" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(<span class="fu">select</span>(sales_data, Sales_Amount, Units_Sold,</span>
<span id="cb97-3"><a href="summarizing-data.html#cb97-3" tabindex="-1"></a>    Customer_Age))</span></code></pre></div>
<pre><code>##              vars    n   mean     sd median trimmed    mad min     max   range
## Sales_Amount    1 5000 279.29 282.95 202.95  226.90 218.36  10 2181.03 2171.03
## Units_Sold      2 5000   6.35   4.97   5.00    5.64   4.45   1   20.00   19.00
## Customer_Age    3 5000  35.58  11.07  35.00   35.19  11.86  18   80.00   62.00
##              skew kurtosis   se
## Sales_Amount 1.75     3.59 4.00
## Units_Sold   1.06     0.36 0.07
## Customer_Age 0.32    -0.36 0.16</code></pre>
<p>You can see that the output contains measures of central tendency (e.g., the mean) and dispersion (e.g., standard deviation) for the selected variables. It can be seen, for example, that the mean of the sales amount variable is 279.29 while the median is 202.95. This already tells us something about the distribution of the data. Because the mean is higher (though not as substantially as it could get, in theory) than the median, we can conclude that there are a some purchases that costed somewhat more than others, potentially resulting in a right skew of the distribution. The median as a measure of central tendency is generally less susceptible to outliers.</p>
<p>In the above command, we used the <code>psych::</code> prefix to avoid confusion and to make sure that R uses the <code>describe()</code> function from the <code>psych</code> package since there are many other packages that also contain a <code>desribe()</code> function. Note that you could also compute these statistics separately by using the respective functions (e.g., <code>mean()</code>, <code>sd()</code>, <code>median()</code>, <code>min()</code>, <code>max()</code>, etc.). There are many options for additional statistics for this function. For example, you could add the argument <code>IQR = TRUE</code> to add the interquartile range to the output.</p>
<p>The <code>psych</code> package also contains the <code>describeBy()</code> function, which lets you compute the summary statistics by sub-groups separately. For example, we could compute the summary statistics by category as follows:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="summarizing-data.html#cb99-1" tabindex="-1"></a><span class="fu">describeBy</span>(<span class="fu">select</span>(sales_data, Sales_Amount, Units_Sold,</span>
<span id="cb99-2"><a href="summarizing-data.html#cb99-2" tabindex="-1"></a>    Customer_Age), sales_data<span class="sc">$</span>Category, <span class="at">skew =</span> <span class="cn">FALSE</span>,</span>
<span id="cb99-3"><a href="summarizing-data.html#cb99-3" tabindex="-1"></a>    <span class="at">range =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: Clothing
##              vars    n   mean     sd   se
## Sales_Amount    1 1265 338.44 118.93 3.34
## Units_Sold      2 1265   5.55   2.88 0.08
## Customer_Age    3 1265  35.62  11.10 0.31
## ------------------------------------------------------------ 
## group: Electronics
##              vars   n   mean     sd    se
## Sales_Amount    1 490 854.81 300.01 13.55
## Units_Sold      2 490   1.98   0.83  0.04
## Customer_Age    3 490  35.49  11.31  0.51
## ------------------------------------------------------------ 
## group: Furniture
##              vars   n   mean     sd    se
## Sales_Amount    1 286 711.63 200.33 11.85
## Units_Sold      2 286   1.48   0.50  0.03
## Customer_Age    3 286  35.22  11.37  0.67
## ------------------------------------------------------------ 
## group: Grocery
##              vars    n  mean    sd   se
## Sales_Amount    1 1746 51.73 19.34 0.46
## Units_Sold      2 1746 10.23  5.81 0.14
## Customer_Age    3 1746 35.69 10.92 0.26
## ------------------------------------------------------------ 
## group: Sports
##              vars   n   mean    sd   se
## Sales_Amount    1 603 218.76 92.84 3.78
## Units_Sold      2 603   4.51  2.34 0.10
## Customer_Age    3 603  35.29 10.90 0.44
## ------------------------------------------------------------ 
## group: Toys
##              vars   n   mean    sd   se
## Sales_Amount    1 610 202.83 87.78 3.55
## Units_Sold      2 610   4.53  2.23 0.09
## Customer_Age    3 610  35.72 11.26 0.46</code></pre>
<p>In this example, we used the arguments <code>skew = FALSE</code> and <code>range = FALSE</code> to exclude some statistics from the output.</p>
<p>R is open to user contributions and various users have contributed packages that aim at making it easier for researchers to summarize statistics. For example, the <a href="https://cran.r-project.org/web/packages/summarytools/vignettes/Recommendations-rmarkdown.html" target="_blank">summarytools</a> package can be used to summarize the variables. If you would like to use this package and you are a Mac user, you may need to also install XQuartz (X11) too. To do this, go to <a href="https://www.xquartz.org/" target="_blank">this page</a> and download the XQuartz-2.7.7.dmg, then open the downloaded folder and click XQuartz.pkg and follow the instruction on screen and install XQuartz. If you still encouter an error after installing XQuartz, you may find a solution &lt;a href=“href=”<a href="https://www.xquartz.org/" class="uri">https://www.xquartz.org/</a>” target=“_blank”&gt;here</a>.</p>
<style type="text/css">
 img {   background-color: transparent;   border: 0; }  .st-table td, .st-table th {   padding: 8px; }  .st-table > thead > tr {    background-color: #eeeeee; }  .st-cross-table td {   text-align: center; }  .st-descr-table td {   text-align: right; }  table.st-table th {   text-align: center; }  table.st-table > thead > tr {    background-color: #eeeeee; }  table.st-table td span {   display: block; }  table.st-table > tfoot > tr > td {   border:none; }  .st-container {   width: 100%;   padding-right: 15px;   padding-left: 15px;   margin-right: auto;   margin-left: auto;   margin-top: 15px; }  .st-multiline {   white-space: pre; }  .st-table {     width: auto;     table-layout: auto;     margin-top: 20px;     margin-bottom: 20px;     max-width: 100%;     background-color: transparent;     border-collapse: collapse; }  .st-table > thead > tr > th, .st-table > tbody > tr > th, .st-table > tfoot > tr > th, .st-table > thead > tr > td, .st-table > tbody > tr > td, .st-table > tfoot > tr > td {   vertical-align: middle; }  .st-table-bordered {   border: 1px solid #bbbbbb; }  .st-table-bordered > thead > tr > th, .st-table-bordered > tbody > tr > th, .st-table-bordered > thead > tr > td, .st-table-bordered > tbody > tr > td {   border: 1px solid #cccccc; }  .st-table-bordered > thead > tr > th, .st-table-bordered > thead > tr > td, .st-table thead > tr > th {   border-bottom: none; }  .st-freq-table > thead > tr > th, .st-freq-table > tbody > tr > th, .st-freq-table > tfoot > tr > th, .st-freq-table > thead > tr > td, .st-freq-table > tbody > tr > td, .st-freq-table > tfoot > tr > td, .st-freq-table-nomiss > thead > tr > th, .st-freq-table-nomiss > tbody > tr > th, .st-freq-table-nomiss > tfoot > tr > th, .st-freq-table-nomiss > thead > tr > td, .st-freq-table-nomiss > tbody > tr > td, .st-freq-table-nomiss > tfoot > tr > td, .st-cross-table > thead > tr > th, .st-cross-table > tbody > tr > th, .st-cross-table > tfoot > tr > th, .st-cross-table > thead > tr > td, .st-cross-table > tbody > tr > td, .st-cross-table > tfoot > tr > td {   padding-left: 20px;   padding-right: 20px; }  .st-table-bordered > thead > tr > th, .st-table-bordered > tbody > tr > th, .st-table-bordered > thead > tr > td, .st-table-bordered > tbody > tr > td {   border: 1px solid #cccccc; }  .st-table-striped > tbody > tr:nth-of-type(odd) {   background-color: #ffffff; }  .st-table-striped > tbody > tr:nth-of-type(even) {   background-color: #f9f9f9; }  .st-descr-table > thead > tr > th, .st-descr-table > tbody > tr > th, .st-descr-table > thead > tr > td, .st-descr-table > tbody > tr > td {   padding-left: 24px;   padding-right: 24px;   word-wrap: break-word; }  .st-freq-table, .st-freq-table-nomiss, .st-cross-table {   border: medium none; }  .st-freq-table > thead > tr:nth-child(1) > th:nth-child(1), .st-cross-table > thead > tr:nth-child(1) > th:nth-child(1), .st-cross-table > thead > tr:nth-child(1) > th:nth-child(3) {   border: none;   background-color: #ffffff;   text-align: center; }  .st-protect-top-border {   border-top: 1px solid #cccccc !important; }  .st-ws-char {   display: inline;   color: #999999;   letter-spacing: 0.2em; }  /* Optional classes */ .st-small {   font-size: 13px; }  .st-small td, .st-small th {   padding: 8px; }  .st-small > thead > tr > th, .st-small > tbody > tr > th, .st-small > thead > tr > td, .st-small > tbody > tr > td {   padding-left: 12px;   padding-right: 12px; } </style>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="summarizing-data.html#cb101-1" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span>
<span id="cb101-2"><a href="summarizing-data.html#cb101-2" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">dfSummary</span>(<span class="fu">select</span>(sales_data, Sales_Amount, Units_Sold,</span>
<span id="cb101-3"><a href="summarizing-data.html#cb101-3" tabindex="-1"></a>    Customer_Age, Store, Category, Brand), <span class="at">plain.ascii =</span> <span class="cn">FALSE</span>,</span>
<span id="cb101-4"><a href="summarizing-data.html#cb101-4" tabindex="-1"></a>    <span class="at">style =</span> <span class="st">&quot;grid&quot;</span>, <span class="at">valid.col =</span> <span class="cn">FALSE</span>, <span class="at">tmp.img.dir =</span> <span class="st">&quot;tmp&quot;</span>,</span>
<span id="cb101-5"><a href="summarizing-data.html#cb101-5" tabindex="-1"></a>    <span class="at">graph.magnif =</span> <span class="fl">0.65</span>), <span class="at">method =</span> <span class="st">&quot;render&quot;</span>, <span class="at">headings =</span> <span class="cn">FALSE</span>,</span>
<span id="cb101-6"><a href="summarizing-data.html#cb101-6" tabindex="-1"></a>    <span class="at">footnote =</span> <span class="cn">NA</span>)</span></code></pre></div>
<div class="container st-container"><table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline ">
  <thead>
    <tr>
      <th align="center" class="st-protect-top-border"><strong>No</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Variable</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Stats / Values</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Freqs (% of Valid)</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Graph</strong></th>
      <th align="center" class="st-protect-top-border"><strong>Missing</strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="center">1</td>
      <td align="left">Sales_Amount
[numeric]</td>
      <td align="left" style="padding:8;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">Mean (sd) : 279.3 (283)</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">min &le; med &le; max:</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">10 &le; 202.9 &le; 2181</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">IQR (CV) : 316.1 (1)</td></tr></table></td>
      <td align="left" style="vertical-align:middle">4635 distinct values</td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent;"><img style="border:none;background-color:transparent;padding:0;max-width:max-content;" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGcAAABKCAQAAAAMeoKaAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfpAwoOFR2Lr92ZAAAA3ElEQVRo3u3bQQrCMBQAUSO5o3fQ89g79JS6TUMlhNJk+p3ZiUXySpLFB9PnFqn77AXI+R9OLj8sOwfplWYvsVW56Lz96lE9us5ea2fBNpsccnLIySEnh5wccnLIySEnh5wccnLIySEnh1wwTm498K7m1uyZdZOznVrTZ9bBNpsccnLIySEnh5wccnLIySEnh5wccnLIBeM0B1N17LlbN4c9dwu22eSQk0Ou+2arY13chzn1xT2Xd5jT4o3Ns9PX2M13Omfs2Urlry+X/F/fs3gh6ZKCnwW7CuSQ+wK3kxqlmFevVgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg=="></td>
      <td align="center">0
(0.0%)</td>
    </tr>
    <tr>
      <td align="center">2</td>
      <td align="left">Units_Sold
[integer]</td>
      <td align="left" style="padding:8;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">Mean (sd) : 6.4 (5)</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">min &le; med &le; max:</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">1 &le; 5 &le; 20</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">IQR (CV) : 7 (0.8)</td></tr></table></td>
      <td align="left" style="vertical-align:middle">20 distinct values</td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent;"><img style="border:none;background-color:transparent;padding:0;max-width:max-content;" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGcAAABKCAQAAAAMeoKaAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfpAwoOFR2Lr92ZAAABIElEQVRo3u2bQQ6DIBBFS8MdvUN7HryDp2w3tQ5F6dAgfKb/bYxCzLwIAwZwj4slrr0DoM7/6Hh5M4uOdHe9Q9Mie7+Pi6bXdekd448Ya2zUQYY6yFAHGeogQx1kqIMMdZChDjLUQYY6yFAHGeogQx1kqIMMdZChDjLUQYY6yPijgvBe3x5nST6jM+aSvLHGRh1kqIOMMR2vrxp29lmijUkFOutYtIgxCW2wVeiEzO7XVKyvlkJHNz+YFHXOx1gqoA4yRZlNQ99cV12nbxKvrrMn1g5jfYc6yJzYd8oIVc4/NNVJc52U0Mz/vmXLJjpbEOvM7vNJnP/SWtkyIdZEJw25ZFob/5Lk32AsFTj5Pechz/XdRGNzQxocYqyxUQeZJ1TYOSZOtNhnAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC"></td>
      <td align="center">0
(0.0%)</td>
    </tr>
    <tr>
      <td align="center">3</td>
      <td align="left">Customer_Age
[integer]</td>
      <td align="left" style="padding:8;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">Mean (sd) : 35.6 (11.1)</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">min &le; med &le; max:</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">18 &le; 35 &le; 80</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">IQR (CV) : 16 (0.3)</td></tr></table></td>
      <td align="left" style="vertical-align:middle">57 distinct values</td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent;"><img style="border:none;background-color:transparent;padding:0;max-width:max-content;" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGcAAABKCAQAAAAMeoKaAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfpAwoOFR2Lr92ZAAABEUlEQVRo3u2ZQQ6DMAwEk4o/9g/te+gf+sr22BgJhCziTNydExwIjOI4C9RPycRt9ANI5390lvakOgdZNwvw6R3IRXvzxT2K4d4cvyNdNmQutvOs0P7uLjZKeVmSFZt0yEiHjHTInN53qBunU4e6cbp1zmNnMjJfd9EZN4/JWoF0yEiHjHTISIeMSQVjP/9drrONJ3Ok6AOdI7kZSLZ2pEOmy/uOJfJlLkAnsqEkKzbpkJEOGemQkQ4Z6ZAJyGyWvoE0XKdvIE1WbNIhIx0y0iGTTCd8G7VcnREG61ydEZIVm3TISIfM4M5madu2r2mjdH5t29u0VWwx+PJCba96TffjvZRSHo1qndJgl2RrRzpkvrSRJXNEka0NAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC"></td>
      <td align="center">0
(0.0%)</td>
    </tr>
    <tr>
      <td align="center">4</td>
      <td align="left">Store
[factor]</td>
      <td align="left" style="padding:8;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">1. Store 1</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">2. Store 10</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">3. Store 2</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">4. Store 3</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">5. Store 4</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">6. Store 5</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">7. Store 6</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">8. Store 7</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">9. Store 8</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">10. Store 9</td></tr></table></td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">494</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">9.9%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">506</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">10.1%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">514</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">10.3%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">522</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">10.4%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">461</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">9.2%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">488</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">9.8%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">502</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">10.0%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">465</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">9.3%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">516</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">10.3%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">532</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">10.6%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent;"><img style="border:none;background-color:transparent;padding:0;max-width:max-content;" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABcAAACgCAQAAABN7D/mAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfpAwoOFR2Lr92ZAAAAlUlEQVRYw+3WwQ2AIAyF4da4o0Mwj+7AlHoFpDFEjRT/dzP5DtQ8GnSXlkxN+mU+px9bZZCgu8VFlgLHnkeFP8SLEsQLnhVIqyQVdw6z1m+iGvxc4HKarv47/BtO363AXXAKbAU+IvfV96Am54X9T06BrcBH5O/2nRcH3HWBWdjwvjgLG+6a+1rYQt/hee4U+OuzN/IDwco4fxpwo9kAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII="></td>
      <td align="center">0
(0.0%)</td>
    </tr>
    <tr>
      <td align="center">5</td>
      <td align="left">Category
[factor]</td>
      <td align="left" style="padding:8;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">1. Clothing</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">2. Electronics</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">3. Furniture</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">4. Grocery</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">5. Sports</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">6. Toys</td></tr></table></td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">1265</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">25.3%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">490</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">9.8%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">286</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">5.7%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">1746</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">34.9%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">603</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">12.1%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">610</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">12.2%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent;"><img style="border:none;background-color:transparent;padding:0;max-width:max-content;" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAC8AAABjCAQAAAChtJEwAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfpAwoOFR2Lr92ZAAAAzElEQVRo3u2Yyw2EMAwFNyt6pAjqWXqgSjhilpCP4yBZmXeDoJGwzcgi7J+e+XalO8dP8mKtbsQS7vckZLoezVXwLfuE79qDBz8i/k8K+c+8LkEKKKgxMpL4ZnF+ESEvTa+UEXJrL3wPJnjw4M2D7xN59H2b56P40/dWPfA9mODBj4hHyIlkF3BNRR7wtX9EYrl2z/dgggcP3jz4PpEi3+uX8QLft/TD92CCBz8iHiEnUriAa5VctIDrO+J7MMGDB2+eN31vH9+174w/ALz0I2jnKeKHAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC"></td>
      <td align="center">0
(0.0%)</td>
    </tr>
    <tr>
      <td align="center">6</td>
      <td align="left">Brand
[factor]</td>
      <td align="left" style="padding:8;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">1. Adidas</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">2. Apple</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">3. Ashley</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">4. Costco</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">5. Decathlon</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">6. Fisher-Price</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">7. H&M</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">8. Hasbro</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">9. IKEA</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">10. LEGO</td></tr><tr style="background-color:transparent"><td style="padding:0;margin:0;border:0" align="left">[ 19 others ]</td></tr></table></td>
      <td align="left" style="padding:0;vertical-align:middle"><table style="border-collapse:collapse;border:none;margin:0"><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">238</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">4.8%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">97</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">1.9%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">76</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">1.5%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">350</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">7.0%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">111</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">2.2%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">131</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">2.6%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">254</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">5.1%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">119</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">2.4%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">61</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">1.2%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">121</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">2.4%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr><tr style="background-color:transparent"><td style="padding:0 5px 0 7px;margin:0;border:0" align="right">3442</td><td style="padding:0 2px 0 0;border:0;" align="left">(</td><td style="padding:0;border:0" align="right">68.8%</td><td style="padding:0 4px 0 2px;border:0" align="left">)</td></tr></table></td>
      <td align="left" style="vertical-align:middle;padding:0;background-color:transparent;"><img style="border:none;background-color:transparent;padding:0;max-width:max-content;" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFAAAACwCAQAAAAyXCGkAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfpAwoOFR2Lr92ZAAABWklEQVR42u3cQQ6CMBRF0WLYI4twPbgHV4kDEi0NCGlr3vvx3plxcmIl/LTisCTvbmoAwF835i8e7y/kfVCi8uti3L41pZRSeip1RfZLDBCgOoAA1QFsrbgXO92F14Z8cpCOMFmH08y8pKQetcqK7+Ck9pwB/QIIUB1AgOoAdgYybl0qN8Va4nmZ7XaEY32CjgEEqA4gQHUAW2Pcam1n++2Tw0bc7mnnmsf4b7/EAAGqAwhQHcDWOO2sKfo86DAFfuI4FqA6gADVAfw3IOPWpRi3esa4BVAdQIDqAAJUxzxY08nDBmsuQ9fBaafPUke7SPwCCFAdQIDq7IGcdtbE9lvP2H4DqA4gQHUAAapj+62mw3mQZzsBAgQI0C+AANXZA2ONW46x/dYZ6BdAgOoAAlQXDcju1qWij1sGZUv55b8+VG2vA/slBghQHUCA6gC2FuvXb47ZLzHA1l7gKTv0JK8p/wAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg=="></td>
      <td align="center">0
(0.0%)</td>
    </tr>
  </tbody>
</table></div>
<p>The ‘Missing’ column in the output above gives us information about missing values. It this case, there are no missing values; however, in reality there are usually at least a couple of lost or not recorded values. To get more precise analysis results, we might want to exclude these observations by creating a “complete” subset of our data. Imagine that we have a missing value in the variable “Sales_Amount”; we would create a subset by filtering that hypothetical observation out:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="summarizing-data.html#cb102-1" tabindex="-1"></a>sales_data_full <span class="ot">&lt;-</span> <span class="fu">filter</span>(sales_data, <span class="sc">!</span><span class="fu">is.na</span>(Sales_Amount))</span></code></pre></div>
<p>In the command above, <code>!is.na()</code> is used to filter the rows for observations where the respective variable does not have missing values. The “!” in this case translates to “is not” and the function <code>is.na()</code> checks for missing values. Hence, the entire statement can be read as “select the rows from the ‘sales_data’ data set where the values of the ‘Sales_Amount’ variable are not missing”.</p>
<p>As you can see, the output also includes a visualization of the frequency distribution using a histogram for the continuous variables and a bar chart for the categorical variables. The frequency distribution is an important element that allows us to assign probabilities to observed values if the observations come from a known probability distribution. How to derive these probability statements will be discussed next.</p>
</div>
<div id="using-frequency-distributions-to-go-beyond-the-data" class="section level4 hasAnchor" number="4.1.2.2">
<h4><span class="header-section-number">4.1.2.2</span> Using frequency distributions to go beyond the data<a href="summarizing-data.html#using-frequency-distributions-to-go-beyond-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The frequency distribution can be used to make statements about the probability that a certain observed value will occur if the observations come from a known probability distribution. For normally distributed data, the following table can be used to look up the probability that a certain value will occur. For example, the value of -1.96 has a probability of 2.5% (i.e., .0250).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-14"></span>
<img src="images/prob_table.JPG" alt="Standard normal table" width="70%" />
<p class="caption">
Figure 1.12: Standard normal table
</p>
</div>
<p>There are two things worth noting. First, the normal distribution has two tails as the following figure shows and we need to take the probability mass at each side of the distribution into account. Hence, there is a 2.5% probability of observing a value of -1.96 or smaller and a 2.5% of observing a value of 1.96 or larger. Hence, the probability mass within this interval is 0.95.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-15"></span>
<img src="images/normal_distribution.JPG" alt="Standard normal distribution" width="70%" />
<p class="caption">
Figure 1.13: Standard normal distribution
</p>
</div>
<p>The second point is related to the scale of the distribution. Since the variables that we will collect can be measured at many different scales (e.g., number of streams, duration in milliseconds), we need a way to convert the scale into a standardized measure that would allow us to compare the observations against the values from the probability table. The <strong>standardized variate</strong>, or z-score, allows us to do exactly that. It is computed as follows:</p>
<p><span class="math display">\[\begin{align}
Z=\frac{X_i-\bar{X}}{s}
\end{align}
\]</span></p>
<p>By subtracting the mean of the variable from each observation and dividing by the standard deviation, the data is converted to a scale with mean = 0 and SD = 1, so we can use the tables of probabilities for the normal distribution to see how likely it is that a particular score will occur in the data. In other words, <strong>the z-score tells us how many standard deviations above or below the mean a particular x-value is</strong>.</p>
<p>To see how this works in practice, let’s inspect the distribution of the ‘customer age’ variable from the sales data set. The <code>hist()</code>-function can be used to draw the corresponding histogram.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="summarizing-data.html#cb103-1" tabindex="-1"></a><span class="fu">hist</span>(sales_data<span class="sc">$</span>Customer_Age)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-16"></span>
<img src="04-basic_statistics_files/figure-html/unnamed-chunk-16-1.png" alt="Histogram of tempo variable" width="672" />
<p class="caption">
Figure 4.1: Histogram of tempo variable
</p>
</div>
<p>In this case, the variable is measured on the scale “years lived” (so it takes values from 0 to, potentially, infinity). To standardize this variable, we will subtract the mean of this variable from each observation and then divide by the standard deviation. We can compute the standardized variable by hand as follows:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="summarizing-data.html#cb104-1" tabindex="-1"></a>sales_data<span class="sc">$</span>age_std <span class="ot">&lt;-</span> (sales_data<span class="sc">$</span>Customer_Age <span class="sc">-</span> <span class="fu">mean</span>(sales_data<span class="sc">$</span>Customer_Age))<span class="sc">/</span><span class="fu">sd</span>(sales_data<span class="sc">$</span>Customer_Age)</span>
<span id="cb104-2"><a href="summarizing-data.html#cb104-2" tabindex="-1"></a><span class="co"># sales_data$age_std &lt;-</span></span>
<span id="cb104-3"><a href="summarizing-data.html#cb104-3" tabindex="-1"></a><span class="co"># scale(sales_data$Customer_Age)</span></span></code></pre></div>
<p>If we create the histogram again, we can see that the scale has changed and now we can compare the standardized values to the values we find in the probability table.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="summarizing-data.html#cb105-1" tabindex="-1"></a><span class="fu">hist</span>(sales_data<span class="sc">$</span>age_std)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-18"></span>
<img src="04-basic_statistics_files/figure-html/unnamed-chunk-18-1.png" alt="Histogram of standardized tempo variable" width="672" />
<p class="caption">
Figure 1.15: Histogram of standardized tempo variable
</p>
</div>
<p>Instead of manually comparing the observed values to the values in the table, it is much easier to use the in-built functions to obtain the probabilities. The <code>pnorm()</code>-function gives the probability of obtaining values lower than the indicated values (i.e., the probability mass left of that value). For the value of 1.96, this probability mass is ~0.025, in line with the table above.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="summarizing-data.html#cb106-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">1.96</span>)</span></code></pre></div>
<pre><code>## [1] 0.0249979</code></pre>
<p>To also take the other end of the distribution into consideration, we would need to multiply this value by to. This way, we arrive at a value of 5%.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="summarizing-data.html#cb108-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">1.96</span>) <span class="sc">*</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.04999579</code></pre>
<p>Regarding the standard normal distribution, it is helpful to remember the following numbers, indicating the points on the standard normal distribution, where the sum of the probability mass to the left at the lower end and to the right of the upper end exceed a certain threshold:</p>
<ul>
<li>+/-<strong>1.645</strong> - 10% of probability mass outside this region</li>
<li>+/-<strong>1.960</strong> - 5% of probability mass outside this region</li>
<li>+/-<strong>2.580</strong> - 1% of probability mass outside this region</li>
</ul>
<p>Going back to our example, we could also ask: what is the probability of obtaining the minimum (or maximum) observed value in our data? The minimum value on the standardized scale is:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="summarizing-data.html#cb110-1" tabindex="-1"></a><span class="fu">min</span>(sales_data<span class="sc">$</span>age_std)</span></code></pre></div>
<pre><code>## [1] -1.588711</code></pre>
<p>And the associated probability is:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="summarizing-data.html#cb112-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fu">min</span>(sales_data<span class="sc">$</span>age_std)) <span class="sc">*</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.1121256</code></pre>
<p>Although the probability of observing this minimum value is low, there are very few observations in the extreme regions at each end of the histogram, so this doesn’t seem too unusual. As a rule of thumb, you can remember that 68% of the observations of a normally distributed variable should be within 1 standard deviation of the mean, 95% within 2 standard deviations, and 99.7% within 3 standard deviations. This is also shown in the following plot:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-23"></span>
<img src="images/prob_rule.JPG" alt="The 68, 95, 99.7 rule (source: Wikipedia)" width="70%" />
<p class="caption">
Figure 1.20: The 68, 95, 99.7 rule (source: Wikipedia)
</p>
</div>
<p>In case of our ‘customer age’ variable, we do observe values that are more than 3 standard deviations away from the mean. In this and other instances, checking the standardized values of a variable may help you to identify outliers. For example, if you conducted a survey and you would like to exclude respondents who answered the survey too fast, you may exclude cases with a low probability based on the distribution of the duration variable.</p>

</div>
</div>
</div>
<div id="data-visualization" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Data visualization<a href="summarizing-data.html#data-visualization" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This section discusses the important topic of data visualization and how to produce appropriate graphics to describe your data visually. You should always visualize your data first.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="images/story_telling.PNG" alt="source: https://twitter.com/heyblake/status/1432070055949258752?s=20" width="25%" />
<p class="caption">
Figure 1.2: source: <a href="https://twitter.com/heyblake/status/1432070055949258752?s=20" class="uri">https://twitter.com/heyblake/status/1432070055949258752?s=20</a>
</p>
</div>
<p>The plots we created in the previous chapters used R’s in-built functions. In this section, we will be using the <code>ggplot2</code> package by Hadley Wickham. It has the advantage of being fairly straightforward to learn and being very flexible when it comes to building more complex plots. For a more in depth discussion you can refer to chapter 4 of the book “Discovering Statistics Using R” by Andy Field et al. or read the following chapter from the book <a href="http://r4ds.had.co.nz/data-visualisation.html" target="_blank">“R for Data science”</a> by Hadley Wickham as well as <a href="https://r-graphics.org/" target="_blank">“R Graphics Cookbook”</a> by Winston Chang.</p>
<p>ggplot2 is built around the idea of constructing plots by stacking layers on top of one another. Every plot starts with the <code>ggplot(data)</code> function, after which layers can be added with the “+” symbol. The following figures show the layered structure of creating plots with ggplot.</p>
<p style="text-align:center;">
<img src="https://github.com/IMSMWU/Teaching/raw/master/MRDA2017/Graphics/ggplot2.JPG" alt="DSUR cover" height="250"  />   
<img src="https://github.com/IMSMWU/Teaching/raw/master/MRDA2017/Graphics/ggplot1.JPG" alt="DSUR cover" height="250"  />
</p>
<div id="categorical-variables-1" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Categorical variables<a href="summarizing-data.html#categorical-variables-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="bar-plot" class="section level4 hasAnchor" number="4.2.1.1">
<h4><span class="header-section-number">4.2.1.1</span> Bar plot<a href="summarizing-data.html#bar-plot" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To give you an example of how the graphics are composed, let’s go back to the frequency table from the previous chapter, where we created a table showing the relative frequencies of categories in the sales data set.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="summarizing-data.html#cb114-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb114-2"><a href="summarizing-data.html#cb114-2" tabindex="-1"></a>sales_data <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;https://raw.githubusercontent.com/WU-RDS/RMA/refs/heads/main/data/data_visualization.csv&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;;&quot;</span>) <span class="sc">%&gt;%</span> <span class="co"># pipe data into mutate</span></span>
<span id="cb114-3"><a href="summarizing-data.html#cb114-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">as.Date</span>(Date), <span class="co"># convert to date</span></span>
<span id="cb114-4"><a href="summarizing-data.html#cb114-4" tabindex="-1"></a>         <span class="at">Store =</span> <span class="fu">as.factor</span>(Store), <span class="co"># convert to factor w. new labels</span></span>
<span id="cb114-5"><a href="summarizing-data.html#cb114-5" tabindex="-1"></a>         <span class="at">Category =</span> <span class="fu">as.factor</span>(Category), <span class="co"># convert to factor with values as labels</span></span>
<span id="cb114-6"><a href="summarizing-data.html#cb114-6" tabindex="-1"></a>         <span class="at">Brand =</span> <span class="fu">as.factor</span>(Brand)) <span class="sc">%&gt;%</span></span>
<span id="cb114-7"><a href="summarizing-data.html#cb114-7" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Sales_Amount)) </span>
<span id="cb114-8"><a href="summarizing-data.html#cb114-8" tabindex="-1"></a></span>
<span id="cb114-9"><a href="summarizing-data.html#cb114-9" tabindex="-1"></a><span class="fu">head</span>(sales_data)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Date"],"name":[1],"type":["date"],"align":["right"]},{"label":["Store"],"name":[2],"type":["fct"],"align":["left"]},{"label":["Category"],"name":[3],"type":["fct"],"align":["left"]},{"label":["Brand"],"name":[4],"type":["fct"],"align":["left"]},{"label":["Sales_Amount"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Units_Sold"],"name":[6],"type":["int"],"align":["right"]},{"label":["Customer_Age"],"name":[7],"type":["int"],"align":["right"]}],"data":[{"1":"2023-11-30","2":"Store 3","3":"Grocery","4":"Trader Joe's","5":"26.32","6":"17","7":"29"},{"1":"2023-08-04","2":"Store 1","3":"Toys","4":"Mattel","5":"270.08","6":"5","7":"32"},{"1":"2023-02-26","2":"Store 6","3":"Clothing","4":"Puma","5":"372.76","6":"1","7":"31"},{"1":"2023-07-17","2":"Store 7","3":"Electronics","4":"LG","5":"1235.69","6":"3","7":"38"},{"1":"2023-11-03","2":"Store 4","3":"Furniture","4":"West Elm","5":"825.87","6":"1","7":"31"},{"1":"2023-06-03","2":"Store 1","3":"Grocery","4":"Walmart","5":"61.04","6":"9","7":"18"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>How can we plot this kind of data? Since we have a categorical variable (“category” is a “group” that unites several individual products), we will use a <strong>bar plot</strong>. However, to be able to use the table for your plot, you first need to assign it to an object as a data frame using the <code>as.data.frame()</code>-function.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="summarizing-data.html#cb115-1" tabindex="-1"></a>table_plot_rel <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(sales_data<span class="sc">$</span>Category)))  <span class="co">#relative frequencies</span></span>
<span id="cb115-2"><a href="summarizing-data.html#cb115-2" tabindex="-1"></a><span class="fu">head</span>(table_plot_rel)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Var1"],"name":[1],"type":["fct"],"align":["left"]},{"label":["Freq"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"Clothing","2":"0.2530"},{"1":"Electronics","2":"0.0980"},{"1":"Furniture","2":"0.0572"},{"1":"Grocery","2":"0.3492"},{"1":"Sports","2":"0.1206"},{"1":"Toys","2":"0.1220"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Since <code>Var1</code> is not a very descriptive name, let’s rename the variable to something more meaningful</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="summarizing-data.html#cb116-1" tabindex="-1"></a>table_plot_rel <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">rename</span>(table_plot_rel, <span class="at">Category =</span> <span class="st">&quot;Var1&quot;</span>)</span>
<span id="cb116-2"><a href="summarizing-data.html#cb116-2" tabindex="-1"></a><span class="fu">head</span>(table_plot_rel)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Category"],"name":[1],"type":["fct"],"align":["left"]},{"label":["Freq"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"Clothing","2":"0.2530"},{"1":"Electronics","2":"0.0980"},{"1":"Furniture","2":"0.0572"},{"1":"Grocery","2":"0.3492"},{"1":"Sports","2":"0.1206"},{"1":"Toys","2":"0.1220"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Once we have our data set we can begin constructing the plot. As mentioned previously, we start with the <code>ggplot()</code> function, with the argument specifying the data set to be used. Within the function, we further specify the scales to be used using the aesthetics argument, specifying which variable should be plotted on which axis. In our example, we would like to plot the categories on the x-axis (horizontal axis) and the relative frequencies on the y-axis (vertical axis). The first layer of the plot is simply an empty space with defined axes but without any “filling”.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="summarizing-data.html#cb117-1" tabindex="-1"></a><span class="fu">ggplot</span>(table_plot_rel, <span class="fu">aes</span>(<span class="at">x =</span> Category, <span class="at">y =</span> Freq))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-7"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-7-1.png" alt="Bar chart (step 1)" width="672" />
<p class="caption">
Figure 1.5: Bar chart (step 1)
</p>
</div>
<p>You can see that the coordinate system is empty. This is because so far, we have told R only which variables we would like to plot but we haven’t specified which geometric figures (points, bars, lines, etc.) we would like to use. This is done using the <code>geom_xxx()</code> function (where “xxx” is replaced with the type of figure that you need: geom_line(), geom_boxplot(), etc.) A good overview of the various geom functions can be found <a href="https://github.com/rstudio/cheatsheets/blob/a9d72b61746ceabb94ef247af14b263ab5fbf15f/data-visualization-2.1.pdf" target="_blank">here</a>. In our case, we would like to use a bar chart for which <code>geom_col</code> is appropriate.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="summarizing-data.html#cb118-1" tabindex="-1"></a><span class="fu">ggplot</span>(table_plot_rel, <span class="fu">aes</span>(<span class="at">x =</span> Category, <span class="at">y =</span> Freq)) <span class="sc">+</span></span>
<span id="cb118-2"><a href="summarizing-data.html#cb118-2" tabindex="-1"></a>    <span class="fu">geom_col</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-8"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-8-1.png" alt="Bar chart (step 2)" width="672" />
<p class="caption">
Figure 1.6: Bar chart (step 2)
</p>
</div>
<p>Now we have specified the data (table_plot_rel and specific variables from it - Categories and Freq) and the shape (columns). Specifying this information is essential for plotting data using ggplot. Everything that follows now just serves the purpose of making the plot look nicer by modifying the appearance of the plot. How about some more meaningful axis labels? We can specify the axis labels using the <code>ylab()</code> and <code>xlab()</code> functions:</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="summarizing-data.html#cb119-1" tabindex="-1"></a><span class="fu">ggplot</span>(table_plot_rel, <span class="fu">aes</span>(<span class="at">x =</span> Category, <span class="at">y =</span> Freq)) <span class="sc">+</span></span>
<span id="cb119-2"><a href="summarizing-data.html#cb119-2" tabindex="-1"></a>    <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Relative frequency&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Category&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-9"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-9-1.png" alt="Bar chart (step 3)" width="672" />
<p class="caption">
Figure 1.7: Bar chart (step 3)
</p>
</div>
<p>How about adding some value labels to the bars? This can be done using <code>geom_text()</code>. Note that the <code>sprintf()</code> function is not mandatory and is only added to format the numeric labels here. The function takes two arguments: the first specifies the format wrapped in two <code>%</code> signs. Thus, <code>%.0f</code> means to format the value as a fixed point value with no digits after the decimal point, and <code>%%</code> is a literal that prints a “%” sign. The second argument is simply the numeric value to be used. In this case, the relative frequencies multiplied by 100 to obtain the percentage values. Using the <code>vjust =</code> argument, we can adjust the vertical alignment of the label. In this case, we would like to display the label slightly above the bars.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="summarizing-data.html#cb120-1" tabindex="-1"></a><span class="fu">ggplot</span>(table_plot_rel, <span class="fu">aes</span>(<span class="at">x =</span> Category, <span class="at">y =</span> Freq)) <span class="sc">+</span></span>
<span id="cb120-2"><a href="summarizing-data.html#cb120-2" tabindex="-1"></a>    <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Relative frequency&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Category&quot;</span>) <span class="sc">+</span></span>
<span id="cb120-3"><a href="summarizing-data.html#cb120-3" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">&quot;%.0f%%&quot;</span>, Freq <span class="sc">*</span></span>
<span id="cb120-4"><a href="summarizing-data.html#cb120-4" tabindex="-1"></a>        <span class="dv">100</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-10"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-10-1.png" alt="Bar chart (step 4)" width="672" />
<p class="caption">
Figure 1.8: Bar chart (step 4)
</p>
</div>
<p>We could go ahead and specify the appearance of every single element of the plot now. However, there are also pre-specified themes that include various formatting steps in one singe function. For example <code>theme_minimal()</code> would make the plot appear like this:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="summarizing-data.html#cb121-1" tabindex="-1"></a><span class="fu">ggplot</span>(table_plot_rel, <span class="fu">aes</span>(<span class="at">x =</span> Category, <span class="at">y =</span> Freq)) <span class="sc">+</span></span>
<span id="cb121-2"><a href="summarizing-data.html#cb121-2" tabindex="-1"></a>    <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Relative frequency&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Category&quot;</span>) <span class="sc">+</span></span>
<span id="cb121-3"><a href="summarizing-data.html#cb121-3" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">&quot;%.1f%%&quot;</span>, Freq<span class="sc">/</span><span class="fu">sum</span>(Freq) <span class="sc">*</span></span>
<span id="cb121-4"><a href="summarizing-data.html#cb121-4" tabindex="-1"></a>        <span class="dv">100</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-11"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-11-1.png" alt="Bar chart (step 5)" width="672" />
<p class="caption">
Figure 1.9: Bar chart (step 5)
</p>
</div>
<p>In a next step, let’s prevent the axis labels from overlapping by rotating the labels.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="summarizing-data.html#cb122-1" tabindex="-1"></a><span class="fu">ggplot</span>(table_plot_rel, <span class="fu">aes</span>(<span class="at">x =</span> Category, <span class="at">y =</span> Freq)) <span class="sc">+</span></span>
<span id="cb122-2"><a href="summarizing-data.html#cb122-2" tabindex="-1"></a>    <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Relative frequency&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Category&quot;</span>) <span class="sc">+</span></span>
<span id="cb122-3"><a href="summarizing-data.html#cb122-3" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">&quot;%.1f%%&quot;</span>, Freq<span class="sc">/</span><span class="fu">sum</span>(Freq) <span class="sc">*</span></span>
<span id="cb122-4"><a href="summarizing-data.html#cb122-4" tabindex="-1"></a>        <span class="dv">100</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>,</span>
<span id="cb122-5"><a href="summarizing-data.html#cb122-5" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="fl">0.75</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-12"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-12-1.png" alt="Bar chart (options 1)" width="672" />
<p class="caption">
Figure 1.10: Bar chart (options 1)
</p>
</div>
<p>We could also add a title and combine all labels using the <code>labs</code> function.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="summarizing-data.html#cb123-1" tabindex="-1"></a><span class="fu">ggplot</span>(table_plot_rel, <span class="fu">aes</span>(<span class="at">x =</span> Category, <span class="at">y =</span> Freq)) <span class="sc">+</span></span>
<span id="cb123-2"><a href="summarizing-data.html#cb123-2" tabindex="-1"></a>    <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Category&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Relative frequency&quot;</span>,</span>
<span id="cb123-3"><a href="summarizing-data.html#cb123-3" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Purchases by category&quot;</span>) <span class="sc">+</span> <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">&quot;%.1f%%&quot;</span>,</span>
<span id="cb123-4"><a href="summarizing-data.html#cb123-4" tabindex="-1"></a>    Freq<span class="sc">/</span><span class="fu">sum</span>(Freq) <span class="sc">*</span> <span class="dv">100</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb123-5"><a href="summarizing-data.html#cb123-5" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">0.75</span>),</span>
<span id="cb123-6"><a href="summarizing-data.html#cb123-6" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-13"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-13-1.png" alt="Bar chart (options 1)" width="672" />
<p class="caption">
Figure 1.11: Bar chart (options 1)
</p>
</div>
<p>We could also add some color to the bars using the <code>colorspace</code> library, which comes with a range of <a href="https://colorspace.r-forge.r-project.org/articles/ggplot2_color_scales.html" target="_blank">color palettes</a>. For example the shading of the bar could reflect the frequency:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="summarizing-data.html#cb124-1" tabindex="-1"></a><span class="fu">library</span>(colorspace)</span>
<span id="cb124-2"><a href="summarizing-data.html#cb124-2" tabindex="-1"></a><span class="fu">ggplot</span>(table_plot_rel, <span class="fu">aes</span>(<span class="at">x =</span> Category, <span class="at">y =</span> Freq)) <span class="sc">+</span></span>
<span id="cb124-3"><a href="summarizing-data.html#cb124-3" tabindex="-1"></a>    <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Freq)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Category&quot;</span>,</span>
<span id="cb124-4"><a href="summarizing-data.html#cb124-4" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Relative frequency&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Purchases by category&quot;</span>) <span class="sc">+</span></span>
<span id="cb124-5"><a href="summarizing-data.html#cb124-5" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">&quot;%.1f%%&quot;</span>, Freq<span class="sc">/</span><span class="fu">sum</span>(Freq) <span class="sc">*</span></span>
<span id="cb124-6"><a href="summarizing-data.html#cb124-6" tabindex="-1"></a>        <span class="dv">100</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>,</span>
<span id="cb124-7"><a href="summarizing-data.html#cb124-7" tabindex="-1"></a>    <span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">scale_fill_continuous_sequential</span>(<span class="at">palette =</span> <span class="st">&quot;Blues&quot;</span>) <span class="sc">+</span></span>
<span id="cb124-8"><a href="summarizing-data.html#cb124-8" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">0.75</span>),</span>
<span id="cb124-9"><a href="summarizing-data.html#cb124-9" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>),</span>
<span id="cb124-10"><a href="summarizing-data.html#cb124-10" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-14"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-14-1.png" alt="Bar chart (options 1)" width="672" />
<p class="caption">
Figure 1.12: Bar chart (options 1)
</p>
</div>
<p>Finally, we can reorder the bars by size using <code>fct_reorder</code>. The first argument to the function is the <code>factor</code> we want to reorder (genre) and the second the variable by which we want to order it (frequency):</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="summarizing-data.html#cb125-1" tabindex="-1"></a><span class="fu">ggplot</span>(table_plot_rel, <span class="fu">aes</span>(<span class="at">x =</span> Category, <span class="at">y =</span> Freq)) <span class="sc">+</span></span>
<span id="cb125-2"><a href="summarizing-data.html#cb125-2" tabindex="-1"></a>    <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(Category, Freq), <span class="at">fill =</span> Freq)) <span class="sc">+</span></span>
<span id="cb125-3"><a href="summarizing-data.html#cb125-3" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Category&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Relative frequency&quot;</span>,</span>
<span id="cb125-4"><a href="summarizing-data.html#cb125-4" tabindex="-1"></a>        <span class="at">title =</span> <span class="st">&quot;Purchases by category&quot;</span>) <span class="sc">+</span> <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">&quot;%.1f%%&quot;</span>,</span>
<span id="cb125-5"><a href="summarizing-data.html#cb125-5" tabindex="-1"></a>    Freq<span class="sc">/</span><span class="fu">sum</span>(Freq) <span class="sc">*</span> <span class="dv">100</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb125-6"><a href="summarizing-data.html#cb125-6" tabindex="-1"></a>    <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">scale_fill_continuous_sequential</span>(<span class="at">palette =</span> <span class="st">&quot;Blues&quot;</span>) <span class="sc">+</span></span>
<span id="cb125-7"><a href="summarizing-data.html#cb125-7" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">0.75</span>),</span>
<span id="cb125-8"><a href="summarizing-data.html#cb125-8" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>),</span>
<span id="cb125-9"><a href="summarizing-data.html#cb125-9" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="05-visualization_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<div class="infobox_orange hint">
<p>The default theme in <code>ggplot</code> is <code>theme_classic()</code>. For even more options, check out the <code>ggthemes</code> package, which includes formats for specific publications. You can check out the different themes <a href="https://cran.r-project.org/web/packages/ggthemes/vignettes/ggthemes.html" target="_blank">here</a>. For example <code>theme_economist()</code> uses the formatting of the journal “The Economist”.
There are various similar packages with pre-specified themes, like the <a href="https://github.com/cttobin/ggthemr" target="_blank"><code>ggthemr</code></a> package, the <a href="https://github.com/ricardo-bion/ggtech" target="_blank"><code>ggtech</code></a> package, the <a href="https://github.com/johnmackintosh/rockthemes" target="_blank"><code>rockthemes</code></a> package, or the <a href="https://github.com/Ryo-N7/tvthemes" target="_blank"><code>tvthemes</code></a> package.</p>
</div>
<p>In a next step, we might want to investigate whether the relative frequencies differ between categories in, for exmple, two selected stores: Store 1 and Store 2. For this purpose we first construct the conditional relative frequency table from the previous chapter again. Recall that the latter gives us the relative frequency within a group (in our case genres), as compared to the relative frequency within the entire sample.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="summarizing-data.html#cb126-1" tabindex="-1"></a>store_1_store_2 <span class="ot">&lt;-</span> sales_data <span class="sc">%&gt;%</span></span>
<span id="cb126-2"><a href="summarizing-data.html#cb126-2" tabindex="-1"></a>    <span class="fu">filter</span>(Store <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Store 1&quot;</span>, <span class="st">&quot;Store 2&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb126-3"><a href="summarizing-data.html#cb126-3" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Store =</span> <span class="fu">factor</span>(Store))</span>
<span id="cb126-4"><a href="summarizing-data.html#cb126-4" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">select</span>(store_1_store_2, Category, Store))</span></code></pre></div>
<pre><code>##              Store
## Category      Store 1 Store 2
##   Clothing        130     140
##   Electronics      44      42
##   Furniture        27      29
##   Grocery         170     180
##   Sports           55      62
##   Toys             68      61</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="summarizing-data.html#cb128-1" tabindex="-1"></a>table_plot_cond_rel <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(<span class="fu">select</span>(store_1_store_2,</span>
<span id="cb128-2"><a href="summarizing-data.html#cb128-2" tabindex="-1"></a>    Category, Store)), <span class="dv">2</span>))  <span class="co">#conditional relative frequencies</span></span>
<span id="cb128-3"><a href="summarizing-data.html#cb128-3" tabindex="-1"></a>table_plot_cond_rel</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Category"],"name":[1],"type":["fct"],"align":["left"]},{"label":["Store"],"name":[2],"type":["fct"],"align":["left"]},{"label":["Freq"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"Clothing","2":"Store 1","3":"0.26315789"},{"1":"Electronics","2":"Store 1","3":"0.08906883"},{"1":"Furniture","2":"Store 1","3":"0.05465587"},{"1":"Grocery","2":"Store 1","3":"0.34412955"},{"1":"Sports","2":"Store 1","3":"0.11133603"},{"1":"Toys","2":"Store 1","3":"0.13765182"},{"1":"Clothing","2":"Store 2","3":"0.27237354"},{"1":"Electronics","2":"Store 2","3":"0.08171206"},{"1":"Furniture","2":"Store 2","3":"0.05642023"},{"1":"Grocery","2":"Store 2","3":"0.35019455"},{"1":"Sports","2":"Store 2","3":"0.12062257"},{"1":"Toys","2":"Store 2","3":"0.11867704"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>We can now take these tables to construct plots grouped by explicitness. To achieve this we simply need to add the <code>facet_wrap()</code> function, which replicates a plot multiple times, split by a specified grouping factor. Note that the grouping factor has to be supplied in R’s formula notation, hence it is preceded by a “~” symbol.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="summarizing-data.html#cb129-1" tabindex="-1"></a><span class="fu">ggplot</span>(table_plot_cond_rel, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(Category,</span>
<span id="cb129-2"><a href="summarizing-data.html#cb129-2" tabindex="-1"></a>    Freq), <span class="at">y =</span> Freq)) <span class="sc">+</span> <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Freq)) <span class="sc">+</span></span>
<span id="cb129-3"><a href="summarizing-data.html#cb129-3" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>Store) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Relative frequency&quot;</span>,</span>
<span id="cb129-4"><a href="summarizing-data.html#cb129-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribution of categories for Store 1 and Store 2&quot;</span>) <span class="sc">+</span></span>
<span id="cb129-5"><a href="summarizing-data.html#cb129-5" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">&quot;%.0f%%&quot;</span>, Freq <span class="sc">*</span></span>
<span id="cb129-6"><a href="summarizing-data.html#cb129-6" tabindex="-1"></a>        <span class="dv">100</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>,</span>
<span id="cb129-7"><a href="summarizing-data.html#cb129-7" tabindex="-1"></a>    <span class="dv">1</span>) <span class="sc">+</span> <span class="fu">scale_fill_continuous_sequential</span>(<span class="at">palette =</span> <span class="st">&quot;Blues&quot;</span>) <span class="sc">+</span></span>
<span id="cb129-8"><a href="summarizing-data.html#cb129-8" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">1.1</span>,</span>
<span id="cb129-9"><a href="summarizing-data.html#cb129-9" tabindex="-1"></a>        <span class="at">hjust =</span> <span class="dv">1</span>), <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb129-10"><a href="summarizing-data.html#cb129-10" tabindex="-1"></a>        <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>), <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-17"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-17-1.png" alt="Grouped bar chart (facet_wrap)" width="672" />
<p class="caption">
Figure 1.14: Grouped bar chart (facet_wrap)
</p>
</div>
</div>
</div>
<div id="continuous-variables-1" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Continuous variables<a href="summarizing-data.html#continuous-variables-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="histogram" class="section level4 hasAnchor" number="4.2.2.1">
<h4><span class="header-section-number">4.2.2.1</span> Histogram<a href="summarizing-data.html#histogram" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Histograms can be created for continuous data using the <code>geom_histogram()</code> function. Note that the <code>aes()</code> function only needs one argument here, since a histogram is a plot of the distribution of only one variable. As an example, let’s consider our data set containing the sales data:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="summarizing-data.html#cb130-1" tabindex="-1"></a><span class="fu">head</span>(sales_data)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Date"],"name":[1],"type":["date"],"align":["right"]},{"label":["Store"],"name":[2],"type":["fct"],"align":["left"]},{"label":["Category"],"name":[3],"type":["fct"],"align":["left"]},{"label":["Brand"],"name":[4],"type":["fct"],"align":["left"]},{"label":["Sales_Amount"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Units_Sold"],"name":[6],"type":["int"],"align":["right"]},{"label":["Customer_Age"],"name":[7],"type":["int"],"align":["right"]}],"data":[{"1":"2023-11-30","2":"Store 3","3":"Grocery","4":"Trader Joe's","5":"26.32","6":"17","7":"29"},{"1":"2023-08-04","2":"Store 1","3":"Toys","4":"Mattel","5":"270.08","6":"5","7":"32"},{"1":"2023-02-26","2":"Store 6","3":"Clothing","4":"Puma","5":"372.76","6":"1","7":"31"},{"1":"2023-07-17","2":"Store 7","3":"Electronics","4":"LG","5":"1235.69","6":"3","7":"38"},{"1":"2023-11-03","2":"Store 4","3":"Furniture","4":"West Elm","5":"825.87","6":"1","7":"31"},{"1":"2023-06-03","2":"Store 1","3":"Grocery","4":"Walmart","5":"61.04","6":"9","7":"18"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Now we can create the histogram using <code>geom_histogram()</code>. The argument <code>binwidth</code> specifies the range that each bar spans, <code>col = "white"</code> specifies the border of the bars to be white and <code>fill = "lavenderblush3"</code> sets the inner color of the bars to lavender color. For brevity, we have now also started naming the x and y axis with the single function <code>labs()</code>, instead of using the two distinct functions <code>xlab()</code> and <code>ylab()</code>. Let’s look at the distribution of streams of R&amp;B songs:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="summarizing-data.html#cb131-1" tabindex="-1"></a>sales_data <span class="sc">|&gt;</span></span>
<span id="cb131-2"><a href="summarizing-data.html#cb131-2" tabindex="-1"></a>    <span class="fu">filter</span>(Store <span class="sc">==</span> <span class="st">&quot;Store 1&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb131-3"><a href="summarizing-data.html#cb131-3" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(Sales_Amount)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">50</span>,</span>
<span id="cb131-4"><a href="summarizing-data.html#cb131-4" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;lavenderblush3&quot;</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Amount of sales&quot;</span>,</span>
<span id="cb131-5"><a href="summarizing-data.html#cb131-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Frequency&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Distribution of sales in Store 1&quot;</span>) <span class="sc">+</span></span>
<span id="cb131-6"><a href="summarizing-data.html#cb131-6" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-19"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-19-1.png" alt="Histogram" width="672" />
<p class="caption">
Figure 1.16: Histogram
</p>
</div>
<p>If you would like to highlight certain points of the distribution, you can use the <code>geom_vline</code> (short for vertical line) function to do this. For example, we may want to highlight the mean and the median of the distribution.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="summarizing-data.html#cb132-1" tabindex="-1"></a>sales_data <span class="sc">|&gt;</span></span>
<span id="cb132-2"><a href="summarizing-data.html#cb132-2" tabindex="-1"></a>    <span class="fu">filter</span>(Store <span class="sc">==</span> <span class="st">&quot;Store 1&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb132-3"><a href="summarizing-data.html#cb132-3" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(Sales_Amount)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">50</span>,</span>
<span id="cb132-4"><a href="summarizing-data.html#cb132-4" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;lavenderblush3&quot;</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Amount of sales&quot;</span>,</span>
<span id="cb132-5"><a href="summarizing-data.html#cb132-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Frequency&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Distribution of sales in Store 1&quot;</span>,</span>
<span id="cb132-6"><a href="summarizing-data.html#cb132-6" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">&quot;Red vertical line = mean, green vertical line = median&quot;</span>) <span class="sc">+</span></span>
<span id="cb132-7"><a href="summarizing-data.html#cb132-7" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(Sales_Amount)),</span>
<span id="cb132-8"><a href="summarizing-data.html#cb132-8" tabindex="-1"></a>        <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">median</span>(Sales_Amount)),</span>
<span id="cb132-9"><a href="summarizing-data.html#cb132-9" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;green&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-20"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-20-1.png" alt="Histogram 2" width="672" />
<p class="caption">
Figure 1.17: Histogram 2
</p>
</div>
<p>In this case, you should indicate what the lines refer to. In the plot above, the ‘subtitle’ argument was used to add this information to the plot.</p>
<div class="infobox_orange hint">
<p>Note the difference between a bar chart and the histogram. While a bar chart is used to visualize the <strong>frequency of observations</strong> for each category of the selected categorical variable, the histogram shows the <strong>frequency distribution</strong> for continuous variables.</p>
</div>
</div>
<div id="boxplot" class="section level4 hasAnchor" number="4.2.2.2">
<h4><span class="header-section-number">4.2.2.2</span> Boxplot<a href="summarizing-data.html#boxplot" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Another common way to display the distribution of continuous variables is through boxplots. ggplot will construct a boxplot if given the geom <code>geom_boxplot()</code>. In our case we might want to show the difference in sales amount between the categories.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="summarizing-data.html#cb133-1" tabindex="-1"></a><span class="fu">ggplot</span>(sales_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(Category, Sales_Amount),</span>
<span id="cb133-2"><a href="summarizing-data.html#cb133-2" tabindex="-1"></a>    <span class="at">y =</span> Sales_Amount)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">coef =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Category&quot;</span>,</span>
<span id="cb133-3"><a href="summarizing-data.html#cb133-3" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Revenue per purchase&quot;</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb133-4"><a href="summarizing-data.html#cb133-4" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>),</span>
<span id="cb133-5"><a href="summarizing-data.html#cb133-5" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-21"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-21-1.png" alt="Boxplot by group" width="672" />
<p class="caption">
Figure 1.18: Boxplot by group
</p>
</div>
<p>The following graphic shows you how to interpret the boxplot:</p>
<div class="float">
<img src="https://github.com/IMSMWU/Teaching/raw/master/MRDA2017/boxplot.JPG" alt="Information contained in a Boxplot" />
<div class="figcaption">Information contained in a Boxplot</div>
</div>
<p>It is often meaningful to augment the boxplot with the data points using <code>geom_jitter()</code>. This way, differences in the distribution of the variable between the genres become even more apparent.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="summarizing-data.html#cb134-1" tabindex="-1"></a><span class="fu">ggplot</span>(sales_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(Category, Sales_Amount),</span>
<span id="cb134-2"><a href="summarizing-data.html#cb134-2" tabindex="-1"></a>    <span class="at">y =</span> Sales_Amount)) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">colour =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb134-3"><a href="summarizing-data.html#cb134-3" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">coef =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb134-4"><a href="summarizing-data.html#cb134-4" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Category&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Revenue per purchase&quot;</span>) <span class="sc">+</span></span>
<span id="cb134-5"><a href="summarizing-data.html#cb134-5" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-22"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-22-1.png" alt="Boxplot by group" width="672" />
<p class="caption">
Figure 1.19: Boxplot by group
</p>
</div>
<p>In case you would like to create the boxplot on the total data (i.e., not by group), just leave the <code>x =</code> argument within the <code>aes()</code> function empty:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="summarizing-data.html#cb135-1" tabindex="-1"></a><span class="fu">ggplot</span>(sales_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> Sales_Amount)) <span class="sc">+</span></span>
<span id="cb135-2"><a href="summarizing-data.html#cb135-2" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">coef =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb135-3"><a href="summarizing-data.html#cb135-3" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Revenue per purchase&quot;</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-23"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-23-1.png" alt="Single Boxplot" width="672" />
<p class="caption">
Figure 1.20: Single Boxplot
</p>
</div>
</div>
<div id="plot-of-means" class="section level4 hasAnchor" number="4.2.2.3">
<h4><span class="header-section-number">4.2.2.3</span> Plot of means<a href="summarizing-data.html#plot-of-means" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Another way to get an overview of the difference between two groups is to plot their respective means with confidence intervals. The mean and confidence intervals will enter the plot separately, using the geoms <code>geom_bar()</code> and <code>geom_errorbar()</code>. Don’t worry if you don’t know exactly how to interpret the confidence interval at this stage - we will cover this topic in the next chapter. Let’s assume we would like to plot the difference in sales amounts between the Groceries and all other categories. For this, we first need to create a dummy variable (i.e., a categorical variable with two levels) that indicates if a purchase is from the Groceries category or from any of the other categories. We can use the <code>ifelse()</code> function to do this, which takes 3 arguments, namely 1) the if-statement, 2) the returned value if this if-statement is true, and 3) the value if the if-statement is not true.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="summarizing-data.html#cb136-1" tabindex="-1"></a>sales_data<span class="sc">$</span>category_dummy <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>(sales_data<span class="sc">$</span>Category <span class="sc">==</span></span>
<span id="cb136-2"><a href="summarizing-data.html#cb136-2" tabindex="-1"></a>    <span class="st">&quot;Electronics&quot;</span>, <span class="st">&quot;Electronics&quot;</span>, <span class="st">&quot;other&quot;</span>))</span></code></pre></div>
<p>To make plotting the desired comparison easier, we can compute all relevant statistics first, using the <code>summarySE()</code> function from the <code>Rmisc</code> package.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="summarizing-data.html#cb137-1" tabindex="-1"></a><span class="fu">library</span>(Rmisc)</span>
<span id="cb137-2"><a href="summarizing-data.html#cb137-2" tabindex="-1"></a>mean_data <span class="ot">&lt;-</span> <span class="fu">summarySE</span>(sales_data, <span class="at">measurevar =</span> <span class="st">&quot;Sales_Amount&quot;</span>,</span>
<span id="cb137-3"><a href="summarizing-data.html#cb137-3" tabindex="-1"></a>    <span class="at">groupvars =</span> <span class="fu">c</span>(<span class="st">&quot;category_dummy&quot;</span>))</span>
<span id="cb137-4"><a href="summarizing-data.html#cb137-4" tabindex="-1"></a>mean_data</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["category_dummy"],"name":[1],"type":["fct"],"align":["left"]},{"label":["N"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Sales_Amount"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["sd"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["se"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["ci"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"Electronics","2":"490","3":"854.8122","4":"300.0149","5":"13.553291","6":"26.629872"},{"1":"other","2":"4510","3":"216.7648","4":"197.7309","5":"2.944329","6":"5.772328"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The output tells you how many observations there are per group, the mean number of sales amount per group, as well as the group-specific standard deviation, the standard error, and the confidence interval (more on this in the next chapter). You can now create the plot as follows:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="summarizing-data.html#cb138-1" tabindex="-1"></a><span class="fu">ggplot</span>(mean_data, <span class="fu">aes</span>(<span class="at">x =</span> category_dummy, <span class="at">y =</span> Sales_Amount)) <span class="sc">+</span></span>
<span id="cb138-2"><a href="summarizing-data.html#cb138-2" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.9</span>), <span class="at">colour =</span> <span class="st">&quot;white&quot;</span>,</span>
<span id="cb138-3"><a href="summarizing-data.html#cb138-3" tabindex="-1"></a>        <span class="at">fill =</span> <span class="st">&quot;lavenderblush3&quot;</span>, <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>,</span>
<span id="cb138-4"><a href="summarizing-data.html#cb138-4" tabindex="-1"></a>        <span class="at">width =</span> <span class="fl">0.65</span>) <span class="sc">+</span> <span class="fu">geom_errorbar</span>(<span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.9</span>),</span>
<span id="cb138-5"><a href="summarizing-data.html#cb138-5" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.15</span>, <span class="fu">aes</span>(<span class="at">ymin =</span> Sales_Amount <span class="sc">-</span> ci, <span class="at">ymax =</span> Sales_Amount <span class="sc">+</span></span>
<span id="cb138-6"><a href="summarizing-data.html#cb138-6" tabindex="-1"></a>        ci)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Category&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Average amount of sales&quot;</span>,</span>
<span id="cb138-7"><a href="summarizing-data.html#cb138-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Average amount of sales by category&quot;</span>) <span class="sc">+</span></span>
<span id="cb138-8"><a href="summarizing-data.html#cb138-8" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb138-9"><a href="summarizing-data.html#cb138-9" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-26"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-26-1.png" alt="Plot of means" width="672" />
<p class="caption">
Figure 1.23: Plot of means
</p>
</div>
<p>As can be seen, there is a large difference between the categories with respect to the average amount of sales.</p>
</div>
<div id="grouped-plot-of-means" class="section level4 hasAnchor" number="4.2.2.4">
<h4><span class="header-section-number">4.2.2.4</span> Grouped plot of means<a href="summarizing-data.html#grouped-plot-of-means" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We might also be interested to investigate a second factor. Say, we would like to find out if there is a difference between categories with respect to the store (i.e., whether the purchase vas made in Store 1 or Store 2). Can we find evidence that products from electronics category sell better in one store than in another. We can compute the statistics using the <code>summarySE()</code> function by simply adding the second variable (Store) to the ‘groupvars’ argument.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="summarizing-data.html#cb139-1" tabindex="-1"></a>mean_data2 <span class="ot">&lt;-</span> sales_data <span class="sc">%&gt;%</span></span>
<span id="cb139-2"><a href="summarizing-data.html#cb139-2" tabindex="-1"></a>    <span class="fu">filter</span>(Store <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Store 1&quot;</span>, <span class="st">&quot;Store 2&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb139-3"><a href="summarizing-data.html#cb139-3" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Store =</span> <span class="fu">factor</span>(Store))</span>
<span id="cb139-4"><a href="summarizing-data.html#cb139-4" tabindex="-1"></a>mean_data2 <span class="ot">&lt;-</span> <span class="fu">summarySE</span>(mean_data2, <span class="at">measurevar =</span> <span class="st">&quot;Sales_Amount&quot;</span>,</span>
<span id="cb139-5"><a href="summarizing-data.html#cb139-5" tabindex="-1"></a>    <span class="at">groupvars =</span> <span class="fu">c</span>(<span class="st">&quot;category_dummy&quot;</span>, <span class="st">&quot;Store&quot;</span>))</span>
<span id="cb139-6"><a href="summarizing-data.html#cb139-6" tabindex="-1"></a>mean_data2</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["category_dummy"],"name":[1],"type":["fct"],"align":["left"]},{"label":["Store"],"name":[2],"type":["fct"],"align":["left"]},{"label":["N"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Sales_Amount"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["sd"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["se"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["ci"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"Electronics","2":"Store 1","3":"44","4":"854.8859","5":"338.5617","6":"51.040098","7":"102.93217"},{"1":"Electronics","2":"Store 2","3":"42","4":"881.1724","5":"315.5578","6":"48.691625","7":"98.33473"},{"1":"other","2":"Store 1","3":"450","4":"214.6190","5":"185.9798","6":"8.767174","7":"17.22979"},{"1":"other","2":"Store 2","3":"472","4":"215.7474","5":"195.2139","6":"8.985447","7":"17.65652"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Now we obtained the results for four different groups (2 categories x 2 stores) and we can amend the plot easily by adding the ‘fill’ argument to the <code>ggplot()</code> function. The <code>scale_fill_manual()</code> function is optional and specifies the color of the bars manually.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="summarizing-data.html#cb140-1" tabindex="-1"></a><span class="fu">ggplot</span>(mean_data2, <span class="fu">aes</span>(<span class="at">x =</span> category_dummy, <span class="at">y =</span> Sales_Amount,</span>
<span id="cb140-2"><a href="summarizing-data.html#cb140-2" tabindex="-1"></a>    <span class="at">fill =</span> Store)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.9</span>),</span>
<span id="cb140-3"><a href="summarizing-data.html#cb140-3" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">&quot;white&quot;</span>, <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> <span class="fu">geom_errorbar</span>(<span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.9</span>),</span>
<span id="cb140-4"><a href="summarizing-data.html#cb140-4" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.2</span>, <span class="fu">aes</span>(<span class="at">ymin =</span> Sales_Amount <span class="sc">-</span> ci, <span class="at">ymax =</span> Sales_Amount <span class="sc">+</span></span>
<span id="cb140-5"><a href="summarizing-data.html#cb140-5" tabindex="-1"></a>        ci)) <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;lavenderblush3&quot;</span>,</span>
<span id="cb140-6"><a href="summarizing-data.html#cb140-6" tabindex="-1"></a>    <span class="st">&quot;grey90&quot;</span>)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Category&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Average amount of sales&quot;</span>,</span>
<span id="cb140-7"><a href="summarizing-data.html#cb140-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Average amount of sales by category and store&quot;</span>) <span class="sc">+</span></span>
<span id="cb140-8"><a href="summarizing-data.html#cb140-8" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb140-9"><a href="summarizing-data.html#cb140-9" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-28"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-28-1.png" alt="Grouped plot of means" width="672" />
<p class="caption">
Figure 1.25: Grouped plot of means
</p>
</div>
<p>The results of the analysis show that also in the there is no big difference between sales of electronic products in two stores.</p>
</div>
<div id="scatter-plot" class="section level4 hasAnchor" number="4.2.2.5">
<h4><span class="header-section-number">4.2.2.5</span> Scatter plot<a href="summarizing-data.html#scatter-plot" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The most common way to show the <strong>relationship</strong> between two continuous variables is a scatterplot. As an example, let’s investigate if there is an association between the sales amount and the customer age. The following code creates a scatterplot with some additional components. The <code>geom_smooth()</code> function creates a smoothed line from the data provided. In this particular example we tell the function to draw the best possible straight line (i.e., minimizing the distance between the line and the points) through the data (via the argument <code>method = "lm"</code>). Note that the “shape = 1” argument passed to the <code>geom_point()</code> function produces hollow circles (instead of solid) and the “fill” and “alpha” arguments passed to the <code>geom_smooth()</code> function specify the color and the opacity of the confidence interval, respectively.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="summarizing-data.html#cb141-1" tabindex="-1"></a><span class="fu">ggplot</span>(sales_data, <span class="fu">aes</span>(Sales_Amount, Customer_Age)) <span class="sc">+</span></span>
<span id="cb141-2"><a href="summarizing-data.html#cb141-2" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Genre&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Relative frequency&quot;</span>) <span class="sc">+</span></span>
<span id="cb141-3"><a href="summarizing-data.html#cb141-3" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb141-4"><a href="summarizing-data.html#cb141-4" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Amount spent&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Customer age&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Scatterplot of amount spent and customer age&quot;</span>) <span class="sc">+</span></span>
<span id="cb141-5"><a href="summarizing-data.html#cb141-5" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb141-6"><a href="summarizing-data.html#cb141-6" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-29"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-29-1.png" alt="Scatter plot" width="672" />
<p class="caption">
Figure 4.2: Scatter plot
</p>
</div>
<p>As you can see, there appears to not be any strong relationship between sales amount and customer age.</p>
<div id="grouped-scatter-plot" class="section level5 hasAnchor" number="4.2.2.5.1">
<h5><span class="header-section-number">4.2.2.5.1</span> Grouped scatter plot<a href="summarizing-data.html#grouped-scatter-plot" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>It could be that customers of different ages shop differently by category. We can visually capture such differences with a grouped scatter plot. By adding the argument <code>colour = Category</code> to the aesthetic specification, ggplot automatically treats the categories as distinct groups and plots accordingly.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="summarizing-data.html#cb142-1" tabindex="-1"></a><span class="fu">ggplot</span>(sales_data, <span class="fu">aes</span>(Sales_Amount, Customer_Age,</span>
<span id="cb142-2"><a href="summarizing-data.html#cb142-2" tabindex="-1"></a>    <span class="at">colour =</span> Category)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb142-3"><a href="summarizing-data.html#cb142-3" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Revenue per purchase&quot;</span>,</span>
<span id="cb142-4"><a href="summarizing-data.html#cb142-4" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Age&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Scatterplot of revenue and age by product category&quot;</span>,</span>
<span id="cb142-5"><a href="summarizing-data.html#cb142-5" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">&quot;Category&quot;</span>) <span class="sc">+</span> <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;lightblue&quot;</span>,</span>
<span id="cb142-6"><a href="summarizing-data.html#cb142-6" tabindex="-1"></a>    <span class="st">&quot;darkblue&quot;</span>, <span class="st">&quot;lavenderblush3&quot;</span>, <span class="st">&quot;red3&quot;</span>, <span class="st">&quot;green4&quot;</span>,</span>
<span id="cb142-7"><a href="summarizing-data.html#cb142-7" tabindex="-1"></a>    <span class="st">&quot;gold2&quot;</span>)) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb142-8"><a href="summarizing-data.html#cb142-8" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-30"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-30-1.png" alt="Grouped scatter plot" width="672" />
<p class="caption">
Figure 4.3: Grouped scatter plot
</p>
</div>
<p>It appears from the plot that there is a reverse association between sales amount and customer age in, for example, toys category.</p>
</div>
</div>
<div id="line-plot" class="section level4 hasAnchor" number="4.2.2.6">
<h4><span class="header-section-number">4.2.2.6</span> Line plot<a href="summarizing-data.html#line-plot" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Another important type of plot is the line plot used if, for example, you have a variable that changes over time and you want to plot how it develops over time. To demonstrate this we will investigate the same data set but focus on sales amount over time. Let’s start with subsetting the data from only one category, for example, Clothing.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="summarizing-data.html#cb143-1" tabindex="-1"></a>sales_data_clothing <span class="ot">&lt;-</span> <span class="fu">filter</span>(sales_data, Category <span class="sc">==</span></span>
<span id="cb143-2"><a href="summarizing-data.html#cb143-2" tabindex="-1"></a>    <span class="st">&quot;Clothing&quot;</span>)</span></code></pre></div>
<p>Given the correct <code>aes()</code> and geom specification ggplot constructs the correct plot for us. In order to make large numbers more readable we use the <code>label_comma</code> function from the <code>scales</code> package in the <code>scale_y_continuous</code> layer.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="summarizing-data.html#cb144-1" tabindex="-1"></a>sales_data_clothing <span class="sc">%&gt;%</span></span>
<span id="cb144-2"><a href="summarizing-data.html#cb144-2" tabindex="-1"></a>    <span class="fu">group_by</span>(Date) <span class="sc">%&gt;%</span></span>
<span id="cb144-3"><a href="summarizing-data.html#cb144-3" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">total_sales =</span> <span class="fu">sum</span>(Sales_Amount)) <span class="sc">%&gt;%</span></span>
<span id="cb144-4"><a href="summarizing-data.html#cb144-4" tabindex="-1"></a>    <span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> total_sales)) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;lavenderblush4&quot;</span>) <span class="sc">+</span></span>
<span id="cb144-5"><a href="summarizing-data.html#cb144-5" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Total sales of clothing (EUR)&quot;</span>,</span>
<span id="cb144-6"><a href="summarizing-data.html#cb144-6" tabindex="-1"></a>        <span class="at">title =</span> <span class="st">&quot;Daily revenues in clothing category&quot;</span>) <span class="sc">+</span></span>
<span id="cb144-7"><a href="summarizing-data.html#cb144-7" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_comma</span>()) <span class="sc">+</span></span>
<span id="cb144-8"><a href="summarizing-data.html#cb144-8" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-32"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-32-1.png" alt="Line plot" width="672" />
<p class="caption">
Figure 4.4: Line plot
</p>
</div>
<p>For better readability, we can aggregate the data by weeks (i.e., obtain total weekly sales) instead of days:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="summarizing-data.html#cb145-1" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb145-2"><a href="summarizing-data.html#cb145-2" tabindex="-1"></a>sales_clothing_weekly <span class="ot">&lt;-</span> sales_data_clothing <span class="sc">%&gt;%</span></span>
<span id="cb145-3"><a href="summarizing-data.html#cb145-3" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Week =</span> <span class="fu">floor_date</span>(Date, <span class="st">&quot;week&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb145-4"><a href="summarizing-data.html#cb145-4" tabindex="-1"></a>    <span class="fu">filter</span>(Week <span class="sc">&lt;</span> <span class="fu">max</span>(Week)) <span class="sc">%&gt;%</span></span>
<span id="cb145-5"><a href="summarizing-data.html#cb145-5" tabindex="-1"></a>    <span class="fu">group_by</span>(Week) <span class="sc">%&gt;%</span></span>
<span id="cb145-6"><a href="summarizing-data.html#cb145-6" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">Weekly_Sales =</span> <span class="fu">sum</span>(Sales_Amount))</span>
<span id="cb145-7"><a href="summarizing-data.html#cb145-7" tabindex="-1"></a></span>
<span id="cb145-8"><a href="summarizing-data.html#cb145-8" tabindex="-1"></a><span class="fu">ggplot</span>(sales_clothing_weekly, <span class="fu">aes</span>(<span class="at">x =</span> Week, <span class="at">y =</span> Weekly_Sales)) <span class="sc">+</span></span>
<span id="cb145-9"><a href="summarizing-data.html#cb145-9" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;lavenderblush4&quot;</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb145-10"><a href="summarizing-data.html#cb145-10" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Week&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Total sales of clothing (EUR)&quot;</span>,</span>
<span id="cb145-11"><a href="summarizing-data.html#cb145-11" tabindex="-1"></a>        <span class="at">title =</span> <span class="st">&quot;Weekly revenues in clothing category&quot;</span>) <span class="sc">+</span></span>
<span id="cb145-12"><a href="summarizing-data.html#cb145-12" tabindex="-1"></a>    <span class="fu">scale_x_date</span>(<span class="at">date_labels =</span> <span class="st">&quot;%b %d&quot;</span>, <span class="at">date_breaks =</span> <span class="st">&quot;1 month&quot;</span>) <span class="sc">+</span></span>
<span id="cb145-13"><a href="summarizing-data.html#cb145-13" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">1.1</span>,</span>
<span id="cb145-14"><a href="summarizing-data.html#cb145-14" tabindex="-1"></a>        <span class="at">hjust =</span> <span class="dv">1</span>), <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb145-15"><a href="summarizing-data.html#cb145-15" tabindex="-1"></a>        <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-33"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-33-1.png" alt="Line plot (weekly)" width="672" />
<p class="caption">
Figure 4.5: Line plot (weekly)
</p>
</div>
<p>We can now include the other specified countries in the plot by using the ‘color’ argument.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="summarizing-data.html#cb146-1" tabindex="-1"></a>sales_data_compare <span class="ot">&lt;-</span> <span class="fu">filter</span>(sales_data, Category <span class="sc">%in%</span></span>
<span id="cb146-2"><a href="summarizing-data.html#cb146-2" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">&quot;Clothing&quot;</span>, <span class="st">&quot;Electronics&quot;</span>, <span class="st">&quot;Toys&quot;</span>))</span>
<span id="cb146-3"><a href="summarizing-data.html#cb146-3" tabindex="-1"></a>sales_data_compare <span class="ot">&lt;-</span> sales_data_compare <span class="sc">%&gt;%</span></span>
<span id="cb146-4"><a href="summarizing-data.html#cb146-4" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Month =</span> lubridate<span class="sc">::</span><span class="fu">floor_date</span>(Date,</span>
<span id="cb146-5"><a href="summarizing-data.html#cb146-5" tabindex="-1"></a>        <span class="st">&quot;month&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb146-6"><a href="summarizing-data.html#cb146-6" tabindex="-1"></a>    <span class="fu">group_by</span>(Month, Category) <span class="sc">%&gt;%</span></span>
<span id="cb146-7"><a href="summarizing-data.html#cb146-7" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">Monthly_Sales =</span> <span class="fu">sum</span>(Sales_Amount))</span>
<span id="cb146-8"><a href="summarizing-data.html#cb146-8" tabindex="-1"></a></span>
<span id="cb146-9"><a href="summarizing-data.html#cb146-9" tabindex="-1"></a><span class="fu">ggplot</span>(sales_data_compare, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Monthly_Sales,</span>
<span id="cb146-10"><a href="summarizing-data.html#cb146-10" tabindex="-1"></a>    <span class="at">color =</span> Category)) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Month&quot;</span>,</span>
<span id="cb146-11"><a href="summarizing-data.html#cb146-11" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Sales&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Monthly sales by category&quot;</span>) <span class="sc">+</span></span>
<span id="cb146-12"><a href="summarizing-data.html#cb146-12" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb146-13"><a href="summarizing-data.html#cb146-13" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>)) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_comma</span>()) <span class="sc">+</span></span>
<span id="cb146-14"><a href="summarizing-data.html#cb146-14" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;red3&quot;</span>,</span>
<span id="cb146-15"><a href="summarizing-data.html#cb146-15" tabindex="-1"></a>        <span class="st">&quot;green4&quot;</span>)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>,</span>
<span id="cb146-16"><a href="summarizing-data.html#cb146-16" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="fl">1.1</span>, <span class="at">hjust =</span> <span class="dv">1</span>), <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb146-17"><a href="summarizing-data.html#cb146-17" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-34"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-34-1.png" alt="Line plot (by category)" width="672" />
<p class="caption">
Figure 4.6: Line plot (by category)
</p>
</div>
<p>One issue in plot like this can be that the scales between categories are different (i.e., in clothing category, there are more purchases that eventually sum up to higher monthly revenues). You could also use the <code>facet_wrap()</code> function to create one individual plot by category and specify ‘scales = “free_y”’ so that each individual plot has its own scale on the y-axis.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="summarizing-data.html#cb147-1" tabindex="-1"></a><span class="fu">ggplot</span>(sales_data_compare, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Monthly_Sales)) <span class="sc">+</span></span>
<span id="cb147-2"><a href="summarizing-data.html#cb147-2" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;lavenderblush4&quot;</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Month&quot;</span>,</span>
<span id="cb147-3"><a href="summarizing-data.html#cb147-3" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Sales&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Monthly sales by category&quot;</span>) <span class="sc">+</span></span>
<span id="cb147-4"><a href="summarizing-data.html#cb147-4" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>Category, <span class="at">scales =</span> <span class="st">&quot;free_y&quot;</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb147-5"><a href="summarizing-data.html#cb147-5" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>)) <span class="sc">+</span></span>
<span id="cb147-6"><a href="summarizing-data.html#cb147-6" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_comma</span>()) <span class="sc">+</span></span>
<span id="cb147-7"><a href="summarizing-data.html#cb147-7" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;red3&quot;</span>,</span>
<span id="cb147-8"><a href="summarizing-data.html#cb147-8" tabindex="-1"></a>        <span class="st">&quot;green4&quot;</span>)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>,</span>
<span id="cb147-9"><a href="summarizing-data.html#cb147-9" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="fl">1.1</span>, <span class="at">hjust =</span> <span class="dv">1</span>), <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb147-10"><a href="summarizing-data.html#cb147-10" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-35"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-35-1.png" alt="Line plot (facet wrap)" width="672" />
<p class="caption">
Figure 4.7: Line plot (facet wrap)
</p>
</div>
<p>Now it’s easier to see that the trends are different between categories, specifically, notice the seasonality that is typical for products from the respective product groups.</p>
</div>
</div>
<div id="saving-plots-on-your-device" class="section level3 hasAnchor" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Saving plots on your device<a href="summarizing-data.html#saving-plots-on-your-device" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To save the last displayed plot, simply use the function <code>ggsave()</code>, and it will save the plot to your working directory. Use the arguments <code>height</code>and <code>width</code> to specify the size of the file. You may also choose the file format by adjusting the ending of the file name. E.g., <code>file_name.jpg</code> will create a file in JPG-format, whereas <code>file_name.png</code> saves the file in PNG-format, etc..</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="summarizing-data.html#cb148-1" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;test_plot.jpg&quot;</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">width =</span> <span class="fl">8.5</span>)</span></code></pre></div>
</div>
<div id="ggplot-extensions" class="section level3 hasAnchor" number="4.2.4">
<h3><span class="header-section-number">4.2.4</span> ggplot extensions<a href="summarizing-data.html#ggplot-extensions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As the ggplot2 package became more and more popular over the past years, more and more extensions have been developed by users that can be used for specific purposes that are not yet covered by the standard functionality of ggplot2. You can find a list of the extensions <a href="https://exts.ggplot2.tidyverse.org/gallery/" target="_blank">here</a>. Below, you can find some example for the additional options.</p>
<div id="results-of-statistical-tests-ggstatsplot" class="section level4 hasAnchor" number="4.2.4.1">
<h4><span class="header-section-number">4.2.4.1</span> Results of statistical tests (ggstatsplot)<a href="summarizing-data.html#results-of-statistical-tests-ggstatsplot" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>You may use the <a href="https://indrajeetpatil.github.io/ggstatsplot/index.html" target="_blank">ggstatplot</a> package to augment your plots with the results from statistical tests, such as an ANOVA. You can find a presentation about the capabilities of this package <a href="https://indrajeetpatil.github.io/ggstatsplot_slides/slides/ggstatsplot_presentation.html#1" target="_blank">here</a>. The boxplot below shows an example.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="summarizing-data.html#cb149-1" tabindex="-1"></a><span class="fu">library</span>(ggstatsplot)</span>
<span id="cb149-2"><a href="summarizing-data.html#cb149-2" tabindex="-1"></a>sales_data_anova <span class="ot">&lt;-</span> <span class="fu">filter</span>(sales_data, Category <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Clothing&quot;</span>, <span class="st">&quot;Electronics&quot;</span>,<span class="st">&quot;Toys&quot;</span>,<span class="st">&quot;Furniture&quot;</span>))</span>
<span id="cb149-3"><a href="summarizing-data.html#cb149-3" tabindex="-1"></a><span class="fu">ggbetweenstats</span>(</span>
<span id="cb149-4"><a href="summarizing-data.html#cb149-4" tabindex="-1"></a>   <span class="at">data =</span> sales_data_anova,</span>
<span id="cb149-5"><a href="summarizing-data.html#cb149-5" tabindex="-1"></a>   <span class="at">title =</span> <span class="st">&quot;Sales by category&quot;</span>, <span class="co"># title for the plot</span></span>
<span id="cb149-6"><a href="summarizing-data.html#cb149-6" tabindex="-1"></a>   <span class="at">plot.type =</span> <span class="st">&quot;box&quot;</span>,</span>
<span id="cb149-7"><a href="summarizing-data.html#cb149-7" tabindex="-1"></a>   <span class="at">x =</span> Category, <span class="co"># 4 groups</span></span>
<span id="cb149-8"><a href="summarizing-data.html#cb149-8" tabindex="-1"></a>   <span class="at">y =</span> Sales_Amount,</span>
<span id="cb149-9"><a href="summarizing-data.html#cb149-9" tabindex="-1"></a>   <span class="at">type =</span> <span class="st">&quot;p&quot;</span>, <span class="co"># default</span></span>
<span id="cb149-10"><a href="summarizing-data.html#cb149-10" tabindex="-1"></a>   <span class="at">messages =</span> <span class="cn">FALSE</span>,</span>
<span id="cb149-11"><a href="summarizing-data.html#cb149-11" tabindex="-1"></a>   <span class="at">bf.message =</span> <span class="cn">FALSE</span>,</span>
<span id="cb149-12"><a href="summarizing-data.html#cb149-12" tabindex="-1"></a>   <span class="at">pairwise.comparisons =</span> <span class="cn">TRUE</span> <span class="co"># display results from pairwise comparisons</span></span>
<span id="cb149-13"><a href="summarizing-data.html#cb149-13" tabindex="-1"></a> )</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-37"></span>
<img src="05-visualization_files/figure-html/unnamed-chunk-37-1.png" alt="Boxplot using ggstatsplot package" width="672" />
<p class="caption">
Figure 4.8: Boxplot using ggstatsplot package
</p>
</div>
</div>
</div>
</div>
<div id="learning-check-2" class="section level2 unnumbered hasAnchor">
<h2>Learning check<a href="summarizing-data.html#learning-check-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>(LC2.1) For which data types is it meaningful to compute the mean?</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" />Nominal</label></li>
<li><label><input type="checkbox" />Ordinal</label></li>
<li><label><input type="checkbox" checked="" />Interval</label></li>
<li><label><input type="checkbox" checked="" />Ratio</label></li>
</ul>
<p><strong>(LC2.2) How can you compute the standardized variate of a variable X?</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" checked="" /><span class="math inline">\(Z=\frac{X_i-\bar{X}}{s}\)</span></label></li>
<li><label><input type="checkbox" /><span class="math inline">\(Z=\frac{\bar{X}+X_i}{s}\)</span></label></li>
<li><label><input type="checkbox" /><span class="math inline">\(Z=\frac{s}{\bar{X}+X_i}\)</span></label></li>
<li><label><input type="checkbox" /><span class="math inline">\(Z=s*({\bar{X}+X_i)}\)</span></label></li>
<li><label><input type="checkbox" />None of the above</label></li>
</ul>
<p><strong>You wish to analyze the following data frame ‘df’ containing information about cars</strong></p>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["mpg"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["cyl"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["disp"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["hp"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["drat"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["wt"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["qsec"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["vs"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["am"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["gear"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["carb"],"name":[11],"type":["dbl"],"align":["right"]}],"data":[{"1":"21.0","2":"6","3":"160","4":"110","5":"3.90","6":"2.620","7":"16.46","8":"0","9":"1","10":"4","11":"4"},{"1":"21.0","2":"6","3":"160","4":"110","5":"3.90","6":"2.875","7":"17.02","8":"0","9":"1","10":"4","11":"4"},{"1":"22.8","2":"4","3":"108","4":"93","5":"3.85","6":"2.320","7":"18.61","8":"1","9":"1","10":"4","11":"1"},{"1":"21.4","2":"6","3":"258","4":"110","5":"3.08","6":"3.215","7":"19.44","8":"1","9":"0","10":"3","11":"1"},{"1":"18.7","2":"8","3":"360","4":"175","5":"3.15","6":"3.440","7":"17.02","8":"0","9":"0","10":"3","11":"2"},{"1":"18.1","2":"6","3":"225","4":"105","5":"2.76","6":"3.460","7":"20.22","8":"1","9":"0","10":"3","11":"1"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><strong>(LC2.3) How could you add a new variable containing the z-scores of the variable ‘mpg’ in R?</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" /><code>df$mpg_std &lt;- zscore(df$mpg)</code></label></li>
<li><label><input type="checkbox" /><code>df$mpg_std &lt;- stdv(df$mpg)</code></label></li>
<li><label><input type="checkbox" /><code>df$mpg_std &lt;- std.scale(df$mpg)</code></label></li>
<li><label><input type="checkbox" checked="" /><code>df$mpg_std &lt;- scale(df$mpg)</code></label></li>
<li><label><input type="checkbox" />None of the above</label></li>
</ul>
<p><strong>(LC2.4) How could you produce the below output?</strong></p>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["vars"],"name":[1],"type":["int"],"align":["right"]},{"label":["n"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["mean"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["sd"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["trimmed"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["mad"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["min"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["max"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["range"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["skew"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["kurtosis"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["se"],"name":[13],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"32","3":"146.68750","4":"68.562868","5":"123.00","6":"141.19231","7":"77.095200","8":"52.0","9":"335.0","10":"283.0","11":"0.7260237","12":"-0.1355511","13":"12.1203173"},{"1":"2","2":"32","3":"20.09062","4":"6.026948","5":"19.20","6":"19.69615","7":"5.411490","8":"10.4","9":"33.9","10":"23.5","11":"0.6106550","12":"-0.3727660","13":"1.0654240"},{"1":"3","2":"32","3":"17.84875","4":"1.786943","5":"17.71","6":"17.82769","7":"1.415883","8":"14.5","9":"22.9","10":"8.4","11":"0.3690453","12":"0.3351142","13":"0.3158899"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<ul class="task-list">
<li><label><input type="checkbox" checked="" /><code>describe(select(mtcars, hp, mpg, qsec))</code></label></li>
<li><label><input type="checkbox" /><code>summary(select(mtcars, hp, mpg, qsec))</code></label></li>
<li><label><input type="checkbox" /><code>table(select(mtcars, hp, mpg, qsec))</code></label></li>
<li><label><input type="checkbox" /><code>str(select(mtcars, hp, mpg, qsec))</code></label></li>
<li><label><input type="checkbox" />None of the above</label></li>
</ul>
<p><strong>(LC2.5) The last column “carb” indicates the number of carburetors each model has. By using a function we got to know the number of car models that have a certain number carburetors. Which function helped us to obtain this information?</strong></p>
<pre><code>## 
##  1  2  3  4  6  8 
##  7 10  3 10  1  1</code></pre>
<ul class="task-list">
<li><label><input type="checkbox" /><code>describe(mtcars$carb)</code></label></li>
<li><label><input type="checkbox" checked="" /><code>table(mtcars$carb)</code></label></li>
<li><label><input type="checkbox" /><code>str(mtcars$carb)</code></label></li>
<li><label><input type="checkbox" /><code>prop.table(mtcars$carb)</code></label></li>
<li><label><input type="checkbox" />None of the above</label></li>
</ul>
<p><strong>(LC2.6) What type of data can be meaningfully depicted in a scatter plot?</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" />Two categorical variables</label></li>
<li><label><input type="checkbox" />One categorical and one continuous variable</label></li>
<li><label><input type="checkbox" checked="" />Two continuous variables</label></li>
<li><label><input type="checkbox" />One continuous variable</label></li>
<li><label><input type="checkbox" />None of the above</label></li>
</ul>
<p><strong>(LC2.7) Which statement about the graph below is true?</strong></p>
<p><img src="05-visualization_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<ul class="task-list">
<li><label><input type="checkbox" />This is a bar chart</label></li>
<li><label><input type="checkbox" checked="" />This is a histogram</label></li>
<li><label><input type="checkbox" checked="" />It shows the frequency distribution of a continuous variable</label></li>
<li><label><input type="checkbox" />It shows the frequency distribution of a categorical variable</label></li>
<li><label><input type="checkbox" />None of the above</label></li>
</ul>
<p><strong>(LC2.8) Which statement about the graph below is true?</strong></p>
<p><img src="05-visualization_files/figure-html/unnamed-chunk-42-1.png" width="50%" /></p>
<ul class="task-list">
<li><label><input type="checkbox" />This is a bar chart</label></li>
<li><label><input type="checkbox" checked="" />50% of observations are contained in the gray area</label></li>
<li><label><input type="checkbox" />The horizontal black line indicates the mean</label></li>
<li><label><input type="checkbox" checked="" />This is a boxplot</label></li>
<li><label><input type="checkbox" />None of the above</label></li>
</ul>
<p><strong>(LC2.9) Which function can help you to save a graph made with <code>ggplot()</code>?</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" checked="" /><code>ggsave()</code></label></li>
<li><label><input type="checkbox" /><code>write.plot()</code></label></li>
<li><label><input type="checkbox" /><code>save.plot()</code></label></li>
<li><label><input type="checkbox" /><code>export.plot()</code></label></li>
</ul>
<p><strong>(LC2.10) For a variable that follows a normal distribution, within how many standard deviations of the mean are 95% of values?</strong></p>
<ul class="task-list">
<li><label><input type="checkbox" />1.645</label></li>
<li><label><input type="checkbox" checked="" />1.960</label></li>
<li><label><input type="checkbox" />2.580</label></li>
<li><label><input type="checkbox" />3.210</label></li>
<li><label><input type="checkbox" />None of the above</label></li>
</ul>
</div>
<div id="references-1" class="section level2 unnumbered hasAnchor">
<h2>References<a href="summarizing-data.html#references-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Field, A., Miles J., &amp; Field, Z. (2012). Discovering Statistics Using R. Sage Publications.</li>
<li>Chang, W. (2020). R Graphics Cookbook, 2nd edition (<a href="https://r-graphics.org/" class="uri">https://r-graphics.org/</a>)</li>
<li>Grolemund, G. &amp; Wickham, H. (2020). R for Data Science (<a href="https://r4ds.had.co.nz/" class="uri">https://r4ds.had.co.nz/</a>)</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-handling.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="statistical-inference.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
